### ISSUE TITLE
Class:DataQualityAssessment

### ISSUE THREAD

**Issue by mtrekels** [tdwg/cd#100]
|  |  |
| ---- | ---- |
| **Parent** | ObjectDigitalRecordMetric |
| **Definition** | A quantification of digital records that meet a defined data quality or completeness criterion |
| **Repeatable** | Yes |
| **Relationships** |  |
| **Potential standards/vocabularies/ontologies to adopt** | |
| **Notes** |  |

**Comment by pzermoglio** [comment]
I'd like to point to the [Data Quality Framework ](https://tdwg.github.io/bdq/tg1/site/) defined by the TDWG Data Quality IG. Particulary, see the [Glossary and Controlled Vocabularies](https://tdwg.github.io/bdq/tg1/site/glossary.html) section.

**Comment by mswoodburn** [comment]
Deprecated in favour of MeasurementOrFact class
