### ISSUE TITLE
Property:dataQualityDefinition

### ISSUE THREAD

**Issue by mtrekels** [tdwg/cd#101]
|  |  |
| ---- | ---- |
| **Definition** | Definition of the digitization quality indicator |
| **Existing property** |  |
| **Existing class** |  |
| **Existing property identifier** |  |
| **Format** | Text |
| **Required** |  |
| **Repeatable** | no |
| **Constraints** |  |
| **Examples** | Georeferenced; Verified; Linked to taxonomic authority |
| **Notes** |  |

**Comment by mswoodburn** [comment]
Deprecated in favour of MeasurementOrFact class
