### ISSUE TITLE
Property:dataQualityQuantity

### ISSUE THREAD

**Issue by mtrekels** [tdwg/cd#102]
|  |  |
| ---- | ---- |
| **Definition** | The quantity of object-level digital records that conform to the DigitizationQualityAssessment |
| **Existing property** |  |
| **Existing class** |  |
| **Existing property identifier** |  |
| **Format** | Numeric |
| **Required** |  |
| **Repeatable** | no |
| **Constraints** |  |
| **Examples** | 140; 99; 200,000 |
| **Notes** |  |

**Comment by mswoodburn** [comment]
Deprecated in favour of MeasurementOrFact class
