### ISSUE TITLE
Class:DigitalMediaAssetQuantity

### ISSUE THREAD

**Issue by mtrekels** [tdwg/cd#105]
|  |  |
| ---- | ---- |
| **Parent** | ObjectGroup |
| **Definition** | The number of digital media, which will generally be images, that are associated with a specimen |
| **Repeatable** | Yes |
| **Relationships** | CollectionDescription (1 to many) <-> DigitalMediaAsset (0 to many) |
| **Potential standards/vocabularies/ontologies to adopt** | Audubon Core (https://tdwg.github.io/ac/termlist/) |
| **Notes** |  |

**Comment by qgroom** [comment]
@mswoodburn The name of this class should probably be changed to DigitalMediaAsset.

**Comment by magpiedin** [comment]
Changing the class's name makes sense

**Comment by mswoodburn** [comment]
@qgroom @magpiedin I'd query this name change - doesn't DigitalMediaAsset suggest a class describing an individual asset, whereas DigitalMediaAssetQuantity seemed a better fit with the definition (a metric representing the number of digital media assets related to the objects in the ObjectGroup)? Also more in line with the other metric classes - ObjectQuantity, TaxonQuantity etc.

**Comment by mswoodburn** [comment]
Have changed the title back based on the above, but feel free to query!

**Comment by mswoodburn** [comment]
Deprecated in favour of MeasurementOrFact class
