### ISSUE TITLE
Property:digitalAssetType

### ISSUE THREAD

**Issue by mtrekels** [tdwg/cd#106]
|  |  |
| ---- | ---- |
| **Definition** | The type of digital asset (i.e., electronic file) related to the CollectionDescription |
| **Existing property** |  |
| **Existing class** |  |
| **Existing property identifier** |  |
| **Format** | Text |
| **Required** |  |
| **Repeatable** | No |
| **Constraints** | Controlled vocabulary |
| **Examples** | `StillImage`, `Sound \| MovingImage` |
| **Notes** | Potential vocabulary: DCMI Type Vocabulary https://dublincore.org/specifications/dublin-core/dcmi-terms/#section-7 and 'media type' terms accepted in Audubon Core. Recommended term names for digital assets are "StillImage", "Sound", "MovingImage", "InteractiveResource", and "Text". Following the DC recommendations at http://purl.org/dc/dcmitype/Text, images of text should be given a value of "Text". |

**Comment by mswoodburn** [comment]
Deprecated in favour of MeasurementOrFact class
