### ISSUE TITLE
Property:digitalAssetQuantity

### ISSUE THREAD

**Issue by mtrekels** [tdwg/cd#107]
|  |  |
| ---- | ---- |
| **Definition** | The number of digital asset objects of the defined digitalAssetType associated with the CollectionDescription |
| **Existing property** |  |
| **Existing class** |  |
| **Existing property identifier** |  |
| **Format** | Numeric |
| **Required** |  |
| **Repeatable** | No |
| **Constraints** | A digitalAssetQuantity must have a corresponding digitalAssetQuantityType |
| **Examples** | `25` (digitalAssetQuantity) with `Percentage` (digitalAssetQuantityType) to indicate the percentage of CollectionDescription items with at least one corresponding digital asset. |
| **Notes** |  |

**Comment by mswoodburn** [comment]
Deprecated in favour of MeasurementOrFact class
