### ISSUE TITLE
Property:digitalAssetQuantityType

### ISSUE THREAD

**Issue by mtrekels** [tdwg/cd#108]
|  |  |
| ---- | ---- |
| **Definition** | Type of quantification system used for digitalAssetQuantity |
| **Existing property** |  |
| **Existing class** |  |
| **Existing property identifier** |  |
| **Format** | Text |
| **Required** |  |
| **Repeatable** | No |
| **Constraints** | A digitalAssetQuantityType must have a corresponding digitalAssetQuantity. Controlled vocabulary |
| **Examples** | `25` (digitalAssetQuantity) with `Percentage` (digitalAssetQuantityType) to indicate the percentage of CollectionDescription items with at least one related digital asset. |
| **Notes** | Recommended vocab: 'Unit', 'Percentage', 'GiB', or other defined unit from ISO standard 80000-1:2009 (https://www.iso.org/obp/ui/#iso:std:iso:80000:-1:ed-1:v1:en) |

**Comment by magpiedin** [comment]
Re:controlled vocabs for 'quantity types', [ISO standard 80000-1:2009](https://www.iso.org/obp/ui/#iso:std:iso:80000:-1:ed-1:v1:en) acknowledges that "...quantities and the relations among them are essentially infinite in number and are continually evolving as new fields of science and technology are developed. Thus, it is not possible to list all these quantities and relations in this International Standard; instead, a selection of the more commonly used quantities and the relations among them is presented..."

If we need a starter list of recommended values, one is included in the Notes here, but all ears if there's a more appropriate/existing vocab.

**Comment by mswoodburn** [comment]
Deprecated in favour of MeasurementOrFact class
