### ISSUE TITLE
Property:schemeIdentifier

### ISSUE THREAD

**Issue by mtrekels** [tdwg/cd#110]
|  |  |
| ---- | ---- |
| **Label** | Scheme Identifier |
| **Definition** | An unambiguous reference to the resource within a given context. |
| **Usage** | This is a unique persistent identifier for the CollectionDescriptionScheme. |
| **Existing property** | dc:identifier |
| **Existing class** |  |
| **Existing property identifier** | http://purl.org/dc/terms/identifier |
| **Format** | IRI |
| **Required** | Yes |
| **Repeatable** | No |
| **Constraints** |  |
| **Examples** | `95ebbc10-4257-479a-9696-6cef00bde00e` `10.5072/example-full` |
| **Notes** | This is a unique persistent identifier for the CollectionDescriptionScheme. Enables ObjectGroup records within the scheme to be identified and metrics aggregated according to the scheme definitions. |

**Comment by mswoodburn** [comment]
Deprecated in favour of generic Identifier class
