### ISSUE TITLE
Property:statusStartDate

### ISSUE THREAD

**Issue by mtrekels** [tdwg/cd#122]
|  |  |
| ---- | ---- |
| **Label** | Status Start Date |
| **Definition** | The date on which the recorded status first became applicable. |
| **Usage** |  |
| **Existing property** |  |
| **Existing class** |  |
| **Existing property identifier** |  |
| **Format** | Date |
| **Required** | No |
| **Repeatable** | No |
| **Constraints** |  ISO 8601 date format. See https://www.w3.org/TR/NOTE-datetime |
| **Examples** | `2012-09-27` |
| **Notes** |  |

**Comment by szucsichnikolaus** [comment]
Definition: Start date of a status of the Collection (conservation or development Status?)
Format: Date
Constraint:  ISO 8601 date format, resolved to day, month or year

**Comment by rondlg** [comment]
Development status

**Comment by rondlg** [comment]
Full ISO dates are hard to generate so agreed to use the following format: 
https://www.w3.org/TR/NOTE-datetime

**Comment by essvee** [comment]
Closed after discussion by working group 3rd March 2022 along with [statusEndDate](https://github.com/tdwg/cd/issues/123), replaced by instance of [TemporalCoverage](https://github.com/tdwg/cd/issues/333)
