### ISSUE TITLE
Property:statusEndDate

### ISSUE THREAD

**Issue by mtrekels** [tdwg/cd#123]
|  |  |
| ---- | ---- |
| **Label** | Status End Date |
| **Definition** | The date on which the recorded status stopped being applicable. |
| **Usage** |  |
| **Existing property** |  |
| **Existing class** |  |
| **Existing property identifier** |  |
| **Format** | Date |
| **Required** | No |
| **Repeatable** | No |
| **Constraints** | ISO 8601 date format. See also https://www.w3.org/TR/NOTE-datetime |
| **Examples** | `2012-09-27` |
| **Notes** | This date is not necessarily the end of the collection (e.g. destroyed), but the date that corresponds with the status as recorded in the corresponding Status term. |

**Comment by szucsichnikolaus** [comment]
Definition: End date of a status of the Collection (conservation or development Status?)
Format: Date
Constraint:  ISO 8601 date format, resolved to day, month or year

**Comment by rondlg** [comment]
Development status

**Comment by rondlg** [comment]
Full ISO dates are hard to generate so agreed to use the following format: 
https://www.w3.org/TR/NOTE-datetime

**Comment by jbstatgen** [comment]
How are the statusEndDate and statusStartDate here in CollectionHistory different from the information recorded by [TemporalCoverage](https://github.com/tdwg/cd/issues/333)?
