### ISSUE TITLE
Class:Collector

### ISSUE THREAD

**Issue by mtrekels** [tdwg/cd#130]
|  |  |
| ---- | ---- |
| **Parent** | ObjectGroup |
| **Definition** | Named person known to have collected objects associated with the CollectionDescription |
| **Repeatable** |  |
| **Relationships** |  |
| **Potential standards/vocabularies/ontologies to adopt** | |
| **Notes** | This class is intended to be used when the basis of the collection is a single collector or a small team  |

**Comment by mtrekels** [comment]
Suggesting to remove this class and  replace by Class:Person

see https://github.com/tdwg/cd/issues/219

**Comment by mswoodburn** [comment]
Removed this property in favour of Person class
