### ISSUE TITLE
Property:geographicOriginID

### ISSUE THREAD

**Issue by mtrekels** [tdwg/cd#132]
|  |  |
| ---- | ---- |
| **Label** |  |
| **Definition** | An identifier for the set of location information (data associated with dcterms:Location). May be a global unique identifier or an identifier specific to the data set. |
| **Usage** | An identifier for the location terms specified in `cd:geographicOrigin`. May be a global unique identifier or an identifier specific to the collection. |
| **Existing property** | dwc:locationID |
| **Existing class** | Location |
| **Existing property identifier** | http://rs.tdwg.org/dwc/terms/locationID |
| **Format** | IRI |
| **Required** | No |
| **Repeatable** | Yes |
| **Constraints** |  |
| **Examples** | `https://opencontext.org/subjects/768A875F-E205-4D0B-DE55-BAB7598D0FD1` |
| **Notes** |  |

**Comment by qgroom** [comment]
In Darwin Core `locationID` is a unique identifier for the `location` class. In CD we don't have a `location` class, but the equivalent is the `GeographicOrigin` class. Therefore, we should perhaps have a `geographicOriginId`

**Comment by qgroom** [comment]
Is cd:verbatimLocality really required?
I can't really imagine a scenario where is would either be useful or used.

**Comment by nielsraes** [comment]
**Examples dwc for locationID**: https://opencontext.org/subjects/768A875F-E205-4D0B-DE55-BAB7598D0FD1

I agree with Quentin that geographicOriginID is more according the standard

**Comment by pzermoglio** [comment]
Updating definition to match dwc

| | |
| ------------- | ------------- |
|**Definition** | An identifier for the set of location information (data associated with dcterms:Location). May be a global unique identifier or an identifier specific to the data set.|
| **Dimension** | |	
| **Existing property**	| dwc:locationID
| **Existing class**	| Location
|**Existing property identifier**	|http://rs.tdwg.org/dwc/terms/locationID
| **Format**	|
|**Required**	|
| **Repeatable**	|
|**Constraints**	|
| **Examples**	|https://opencontext.org/subjects/768A875F-E205-4D0B-DE55-BAB7598D0FD1
|**Notes**	|

**Comment by mtrekels** [comment]
Changed the property name

**Comment by mswoodburn** [comment]
Deprecated in favour of generic Identifier class
