### ISSUE TITLE
Property:higherGeographyID

### ISSUE THREAD

**Issue by mtrekels** [tdwg/cd#133]
|  |  |
| ---- | ---- |
| **Label** | Higher Geography ID |
| **Definition** | An identifier for the geographic region within which the Location occurred. |
| **Usage** | An identifier for the geographic region from which the objects in the collection originated. |
| **Existing property** | dwc:higherGeographyID |
| **Existing class** | Location |
| **Existing property identifier** | http://rs.tdwg.org/dwc/terms/higherGeographyID |
| **Format** | IRI |
| **Required** | No |
| **Repeatable** | No |
| **Constraints** | Controlled vocabulary |
| **Examples** | `http://vocab.getty.edu/tgn/1002002` |
| **Notes** | Recommended best practice is to use a persistent identifier from a controlled vocabulary such as the Getty Thesaurus of Geographic Names. |

**Comment by nielsraes** [comment]
Definition dwc: An identifier for the geographic region within which the Location occurred.
Format dwc: Recommended best practice is to use a persistent identifier from a controlled vocabulary such as the Getty Thesaurus of Geographic Names.
Examples dwc: http://vocab.getty.edu/tgn/1002002 (Antártida e Islas del Atlántico Sur, Territorio Nacional de la Tierra del Fuego, Argentina).

Is this useful? Not for me

**Comment by pzermoglio** [comment]
Updating definition to match dwc

| | |
| ------------- | ------------- |
|**Definition** | An identifier for the geographic region within which the Location occurred. |
| **Dimension** | |	
| **Existing property**	| dwc:higherGeographyID
| **Existing class**	| Location
|**Existing property identifier**	|http://rs.tdwg.org/dwc/terms/#higherGeographyID
| **Format**	|
|**Required**	|
| **Repeatable**	|
|**Constraints**	|
| **Examples**	|http://vocab.getty.edu/tgn/1002002 (Antártida e Islas del Atlántico Sur, Territorio Nacional de la Tierra del Fuego, Argentina).
|**Notes**	|Recommended best practice is to use a persistent identifier from a controlled vocabulary such as the Getty Thesaurus of Geographic Names.

**Comment by mswoodburn** [comment]
Issue with term definition not quite matching the dwc definition (ref comment on #131)

**Comment by essvee** [comment]
Property removed from standard: surplus to requirements in the context of other fields in this class. See TDWG CD rolling weekly meeting notes dated 3rd June '21 for rationale and discussion.
