### ISSUE TITLE
Property:higherGeography

### ISSUE THREAD

**Issue by mtrekels** [tdwg/cd#134]
|  |  |
| ---- | ---- |
| **Label** | Higher Geography |
| **Definition** | A list (concatenated and separated) of geographic names less specific than the information captured in the locality term. |
| **Usage** | A list (concatenated and separated) of geographic names less specific than the information captured in the locality term reflecting the geographic region from which items in the collection originated.  |
| **Existing property** | dwc:higherGeography |
| **Existing class** | Location |
| **Existing property identifier** | http://rs.tdwg.org/dwc/terms/higherGeography |
| **Format** | Text |
| **Required** | No |
| **Repeatable** | No |
| **Constraints** |  |
| **Examples** | `North Atlantic Ocean. South America` \| `Argentina` \| `Patagonia` \| `Parque Nacional Nahuel Huapi` \| `Neuquén` \| `Los Lagos` (with accompanying values South America in continent, Argentina in country, Neuquén in stateProvince, and Los Lagos in county). |
| **Notes** |  |

**Comment by nielsraes** [comment]
Definition dwc: A list (concatenated and separated) of geographic names less specific than the information captured in the locality term.
Format dwc: Recommended best practice is to separate the values in a list with space vertical bar space ( | ), with terms in order from least specific to most specific.
Examples dwc: North Atlantic Ocean. South America | Argentina | Patagonia | Parque Nacional Nahuel Huapi | Neuquén | Los Lagos (with accompanying values South America in continent, Argentina in country, Neuquén in stateProvince, and Los Lagos in county).

Is this useful? Especially in combination with higherGeographyID

**Comment by nielsraes** [comment]
http://rs.tdwg.org/dwc/terms/higherGeography

Examples dwc: North Atlantic Ocean. South America | Argentina | Patagonia | Parque Nacional Nahuel Huapi | Neuquén | Los Lagos (with accompanying values South America in continent, Argentina in country, Neuquén in stateProvince, and Los Lagos in county.

**Comment by pzermoglio** [comment]
Updating 

| | |
| ------------- | ------------- |
|**Definition** | A list (concatenated and separated) of geographic names less specific than the information captured in the locality term.|
| **Dimension** | |	
| **Existing property**	| dwc:higherGeography
| **Existing class**	| Location
|**Existing property identifier**	|http://rs.tdwg.org/dwc/terms/higherGeography
| **Format**	|
|**Required**	|
| **Repeatable**	|
|**Constraints**	|
| **Examples**	| North Atlantic Ocean. South America \| Argentina \| Patagonia \| Parque Nacional Nahuel Huapi \| Neuquén \| Los Lagos (with accompanying values South America in continent, Argentina in country, Neuquén in stateProvince, and Los Lagos in county.
|**Notes**	|Recommended best practice is to separate the values in a list with space vertical bar space ( \| ), with terms in order from least specific to most specific.

**Comment by l-tilley** [comment]
For the SYNTHESYS+ Collections Digitisation Dashboard we have used this terminology: 
https://www.tdwg.org/standards/wgsrpd/

**Comment by essvee** [comment]
Property removed from standard: surplus to requirements in the context of other fields in this class. See TDWG CD rolling weekly meeting notes dated 3rd June '21 for rationale and discussion.
