### ISSUE TITLE
Property:verbatimLocality

### ISSUE THREAD

**Issue by mtrekels** [tdwg/cd#145]
|  |  |
| ---- | ---- |
| **Definition** |  |
| **Dimension** |  |
| **Existing property** | dwc:verbatimLocality |
| **Existing class** | Location |
| **Existing property identifier** | http://rs.tdwg.org/dwc/terms/verbatimLocality |
| **Format** |  |
| **Required** |  |
| **Repeatable** |  |
| **Constraints** |  |
| **Examples** |  |
| **Notes** |  |

**Comment by nielsraes** [comment]
I agree with Quentin --> qgroom in localitionID: "Is cd:verbatimLocality really required? I can't really imagine a scenario where is would either be useful or used."

**Comment by qgroom** [comment]
@mswoodburn @debpaul can we delete/deprecate this term?
