### ISSUE TITLE
Property:institutionDescription

### ISSUE THREAD

**Issue by mtrekels** [tdwg/cd#150]
|  |  |
| ---- | ---- |
| **Definition** | Description of institution, suitable for a general audience. |
| **Existing property** | dc:description |
| **Existing class** |  |
| **Existing property identifier** | http://purl.org/dc/elements/1.1/description |
| **Format** | text |
| **Required** | no |
| **Repeatable** |  |
| **Constraints** |  |
| **Examples** |  |
| **Notes** | From NCD |

**Comment by nielsraes** [comment]
What uses GrSciColl for description? https://www.gbif.org/grscicoll/institution/dd6d4fb3-dc6a-4101-b992-61ec12072678

**Comment by mtrekels** [comment]
Closed, as institution is covered by organisationalUnit
