### ISSUE TITLE
Property:parentInstitutionOrNetwork

### ISSUE THREAD

**Issue by mtrekels** [tdwg/cd#152]
|  |  |
| ---- | ---- |
| **Definition** | Name, acronym, identifier or coden of parent institution or network(s) |
| **Existing property** |  |
| **Existing class** |  |
| **Existing property identifier** |  |
| **Format** |  |
| **Required** |  |
| **Repeatable** | Yes |
| **Constraints** |  |
| **Examples** |  |
| **Notes** |  |

**Comment by szucsichnikolaus** [comment]
Format: text

**Comment by mtrekels** [comment]
Closed, as institution is covered by organisationalUnit
