### ISSUE TITLE
Property:institutionWebsiteURL

### ISSUE THREAD

**Issue by mtrekels** [tdwg/cd#153]
|  |  |
| ---- | ---- |
| **Definition** | URL of the institution's main website |
| **Existing property** |  |
| **Existing class** |  |
| **Existing property identifier** |  |
| **Format** | Text |
| **Required** | No  |
| **Repeatable** | No |
| **Constraints** |  |
| **Examples** |  `https://www.naturkundemuseum-bw.de/` |
| **Notes** | Valid URL |

**Comment by MikeTrizna** [comment]
The current example is giving a 403 error. Is the correct SMNS website URL https://www.naturkundemuseum-bw.de/ ?

**Comment by ekrimmel** [comment]
_website:URL_ could be a useful property to have in other classes, e.g. _OrganisationalUnit_. Depending on how people model their collections, sometimes the institution can be very separate from the organizational unit. Field station collections in the US, for instance, are frequently associated with a parent university as their institution but managed entirely separate from the rest of the university and from any other university collections. In terms of using the CD standard to make collections more discoverable, a additional URL in a class more specific than institution could be hugely beneficial.

**Comment by qgroom** [comment]
Sometimes collections have separate websites within the institutional website

**Comment by mtrekels** [comment]
added a new property in the Class:OrganisationalUnit: issue #240

**Comment by mtrekels** [comment]
Closed, as institution is covered by organisationalUnit
