### ISSUE TITLE
Property:institutionIdentifier

### ISSUE THREAD

**Issue by mtrekels** [tdwg/cd#157]
|  |  |
| ---- | ---- |
| **Definition** | An identifier for the institution having custody of the collection referred to in the record. |
| **Existing property** | dwc:institutionID |
| **Existing class** | Record-level |
| **Existing property identifier** | https://dwc.tdwg.org/terms/#dwc:institutionID |
| **Format** | Text |
| **Required** | No |
| **Repeatable** | No |
| **Constraints** |  |
| **Examples** | 99ea0c90-61e5-11dc-a64c-b8a03c50a862; http://biocol.org/urn:lsid:biocol.org:col:34840 |
| **Notes** |  |

**Comment by falkogloeckler** [comment]
We might want to set up contraints that depend on the type of identifiers

**Comment by pzermoglio** [comment]
Would [dwc:institutionID](https://dwc.tdwg.org/terms/#dwc:institutionID) serve for this one?
