### ISSUE TITLE
Property:geologicalContextID

### ISSUE THREAD

**Issue by mtrekels** [tdwg/cd#179]
|  |  |
| ---- | ---- |
| **Label** | Geological Context ID |
| **Definition** | An identifier for the set of information associated with a GeologicalContext (the location within a geological context, such as stratigraphy). May be a global unique identifier or an identifier specific to the data set. |
| **Usage** | An identifier for the set of information associated with the GeologicalContext (the location within a geological context, such as stratigraphy) from which items in the collection originated. May be a global unique identifier or an identifier specific to the data set. |
| **Existing property** | dwc:geologicalContextID |
| **Existing class** | Geological Context |
| **Existing property identifier** | http://rs.tdwg.org/dwc/terms/#geologicalContextID |
| **Format** | IRI |
| **Required** | No |
| **Repeatable** | No |
| **Constraints** |  |
| **Examples** | `https://opencontext.org/subjects/e54377f7-4452-4315-b676-40679b10c4d9` |
| **Notes** |  |

**Comment by mswoodburn** [comment]
Deprecated in favour of generic Identifier class
