### ISSUE TITLE
ICEDIG Use Cases

### ISSUE THREAD

**Issue by debpaul** [tdwg/cd#19]
- [x] Get ICEDIG (Niels Raes) to add use cases (or link to the Use Cases List created for planning recommendations to SYNTHESYS+ for building the Collections Digitization Dashboard for DiSSCo.
- [x] Add them, or a link to them, here https://github.com/tdwg/cd/tree/master/reference/use_cases

**Comment by debpaul** [comment]
@nielsraes do you think this is something you can add to the CDD report you are currently getting ready to deliver for ICEDIG?

**Comment by debpaul** [comment]
@nielsraes, I was wondering if there is a link to the ICEDIG-gathered use cases that we can link to in this TDWG CD repository Use Case page. Perhaps after the current CDD WP group milestone is published (end of March 2019?)

**Comment by nielsraes** [comment]
Hi Deb,

All use cases on CD and dashboarding from the first ICEDIG meeting are
included in the D2.3 deliverable I shared with you. We can make these
available on the dedicated TDWG github repository. We are still working on
the user stories for DiSSCo under ICEDIG T6.2, but these do not directly
refer to CD standards or dashboards.

Best,

Niels
---------------------------------------------------------------------------------------------------------
Dr. Niels Raes
Senior Project Manager
Naturalis Biodiversity Center
International Biodiversity Infrastructures
ORCID: 0000-0002-4329-4892 <http://orcid.org/0000-0002-4329-4892>
Google Scholar
<https://scholar.google.nl/citations?hl=en&user=ErUaTZcAAAAJ&view_op=list_works&sortby=pubdate>

T +31(0)71 751 9136 | M +31(0)6 4578 2356 | Niels.Raes@naturalis.nl |  Skype:
niels.raes | Vondellaan 55 - 5th floor - e05.36, 2332 AA Leiden, P.O. Box
9517, 2300 RA, Leiden, the Netherlands

**Comment by debpaul** [comment]
added ICEDIG use cases to the Use Cases page.
added a copy of the ICEDIG report with use cases in it, to the documents folder.
closing this ticket
