### ISSUE TITLE
Class:OrganisationalUnitIdentifier

### ISSUE THREAD

**Issue by mtrekels** [tdwg/cd#204]
|  |  |
| ---- | ---- |
| **Parent** | OrganisationalUnit |
| **Definition** | Identifier used to refer to the organisational unit responsible for the care and management of the collection described by the record. The fields in this class describe the insitutional affiliation for the physical collection.|
| **Repeatable** | Yes |
| **Relationships** | OrganisationalUnit (1 to many) <-> OrganisationalUnitIdentifier (1 to many) |
| **Potential standards/vocabularies/ontologies to adopt** |  |
| **Notes** |  |

**Comment by mswoodburn** [comment]
Closed as replaced by generic Identifier class
