### ISSUE TITLE
Property:organisationUnitIdentifierSource

### ISSUE THREAD

**Issue by mtrekels** [tdwg/cd#206]
|  |  |
| ---- | ---- |
| **Label** | Organisational Unit Identifier Source |
| **Definition** | URI or Authority that defines the provider of the identifier |
| **Usage** |  |
| **Existing property** |  |
| **Existing class** |  |
| **Existing property identifier** |  |
| **Format** | Text |
| **Required** | No |
| **Repeatable** | No  |
| **Constraints** |  |
| **Examples** | `https://www.gbif.org/grscicoll` `https://grid.ac/` |
| **Notes** | Provider of identifier may be different from the body that originally minted it. This property is not required but you should also complete organisationUnitIdentifierType |

**Comment by mswoodburn** [comment]
Closed as replaced by generic Identifier class
