### ISSUE TITLE
Property:organisationUnitIdentifier

### ISSUE THREAD

**Issue by mtrekels** [tdwg/cd#207]
|  |  |
| ---- | ---- |
| **Label** | Organisational Unit Identifier |
| **Definition** | Value of identifier used to refer to the organisational unit responsible for the care and management of the collection described by the record. |
| **Usage** |  |
| **Existing property** |  |
| **Existing class** |  |
| **Existing property identifier** |  |
| **Format** | Text  |
| **Required** | No |
| **Repeatable** | No |
| **Constraints** |  |
| **Examples** |  [grid.410350.3](https://grid.ac/institutes/grid.410350.3); [131422873](http://viaf.org/viaf/131422873) |
| **Notes** | Ensure organisationalUnitIdentifierType matches the identifier value  |

**Comment by essvee** [comment]
|  |  |
| ---- | ---- |
| **Definition** | Identifier used to refer to the OrganisationalUnit responsible for the care and management of the collection described by the record. |
| **Existing property** |  |
| **Existing class** |  |
| **Existing property identifier** |  |
| **Format** | Text  |
| **Required** | No |
| **Repeatable** | No |
| **Constraints** |  |
| **Examples** | [64232ca4-fd5a-4a3d-a1d5-ef812107472c](https://www.gbif.org/grscicoll/collection/64232ca4-fd5a-4a3d-a1d5-ef812107472c) ; GRIDIdentifier; [WAG](http://sweetgum.nybg.org/science/ih/herbarium-details/?irn=126969); [131422873](http://viaf.org/viaf/131422873); [955b0e63-c3b5-4d74-8dfa-15b384b9ae77](https://www.gbif.org/grscicoll/institution/52827361-5e82-43b7-b92a-f6ad98367fa5) |
| **Notes** |  |

**Comment by essvee** [comment]
Not sure what to put in terms of constraints/existing properties and classes for this one. 

There are existing classes for [organizational-level identifiers](http://rs.tdwg.org/abcd/terms/Organization), but as the overall OrganisationalUnit class can represent any org level from institution down to divisions/smaller operational groups the nature of the constraint/equivalence to other standards is dependent on the properties of the associated OrganizationalUnit class. Or am I overthinking this and we should provide a few different existing classes and make a note that identifier should match the level of the OU class?

**Comment by mswoodburn** [comment]
Closed as replaced by generic Identifier class
