### ISSUE TITLE
Provide links in History/Context

### ISSUE THREAD

**Issue by gkampmeier** [tdwg/cd#21]
Please provide link to the BioCASE project website and an expansion and/or link to RLG Programs and link to RAVNS.

**Comment by debpaul** [comment]
I can do BioCase - can someone suggest site?

But RAVNS I tried - not in existence as far as I can tell.

Sent from Shoe (my iPhone)

On Mar 11, 2019, at 10:12 PM, gkampmeier <notifications@github.com<mailto:notifications@github.com>> wrote:


Please provide link to the BioCASE project website and an expansion and/or link to RLG Programs and link to RAVNS.

**Comment by connierinaldo** [comment]
I don’t think there is a RAVNs site. I believe we worked on base camp.

Sent from my iPhone

On Mar 11, 2019, at 10:57 PM, Debbie Paul <notifications@github.com<mailto:notifications@github.com>> wrote:

I can do BioCase - can someone suggest site?

But RAVNS I tried - not in existence as far as I can tell.

Sent from Shoe (my iPhone)

On Mar 11, 2019, at 10:12 PM, gkampmeier <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com>> wrote:


Please provide link to the BioCASE project website and an expansion and/or link to RLG Programs and link to RAVNS.

**Comment by debpaul** [comment]
Hi @gkampmeier @connierinaldo thanks for your feedback. On the community page (that shows the Interest Group Charter), I added a link to BioCASE, a link to RL|G as well. I also added a reference to RDA. May I request that @stanblum merges these changes and we can close this ticket?

**Comment by debpaul** [comment]
Thanks @stanblum for the merge. Closing this ticket.
