### ISSUE TITLE
Property:organisationalUnitWebsiteURL

### ISSUE THREAD

**Issue by mtrekels** [tdwg/cd#240]
|  |  |
| ---- | ---- |
| **Label** | Organisational Unit Website URL |
| **Definition** | URL of the Organisational Unit's main website |
| **Usage** |  |
| **Existing property** |  |
| **Existing class** |  |
| **Existing property identifier** |  |
| **Format** | Text |
| **Required** | No  |
| **Repeatable** | No |
| **Constraints** |  |
| **Examples** |   |
| **Notes** | Valid/resolvable URL. e.g. institution record URL: https://www.nybg.org/ e.g. collection specific URL: https://www.amnh.org/research/paleontology/collections |

**Comment by mtrekels** [comment]
Good example is needed

**Comment by mswoodburn** [comment]
DEPRECATED in favour of the generic Reference class
