### ISSUE TITLE
Property:taxonID

### ISSUE THREAD

**Issue by nielsraes** [tdwg/cd#288]
|  |  |
| ---- | ---- |
| **Label** |  |
| **Definition** | An identifier for the set of taxon information (data associated with the Taxon class). May be a global unique identifier or an identifier specific to the data set. |
| **Usage** |  |
| **Existing property** | dwc:Taxon |
| **Existing class** | dwc:TaxonID |
| **Existing property identifier** | https://dwc.tdwg.org/terms/taxonID |
| **Format** | String |
| **Required** | No |
| **Repeatable** | No |
| **Constraints** | |
| **Examples** | `https://api.catalogueoflife.org/dataset/3LR/nameusage/8K9Y`, `https://www.gbif.org/species/212`| 
| **Notes** |  |

**Comment by mswoodburn** [comment]
DEPRECATED in favour of the generic Identifier class
