### ISSUE TITLE
Property:measurementDeterminedDate

### ISSUE THREAD

**Issue by mswoodburn** [tdwg/cd#296]
|  |  |
| ---- | ---- |
| **Label** | Measurement Determined Date |
| **Definition** | The date on which the MeasurementOrFact was made. |
| **Usage** | The date on which the MeasurementOrFact about the collection was made. |
| **Existing property** | dwc:measurementDeterminedDate |
| **Existing class** | dwc:MeasurementOrFact |
| **Existing property identifier** | http://rs.tdwg.org/dwc/terms/measurementDeterminedDate |
| **Format** | Date |
| **Required** | No |
| **Repeatable** | No |
| **Constraints** | Date format conforming to https://www.w3.org/TR/NOTE-datetime date format, resolved to day, month or year. |
| **Examples** | `1886`, `1984-09`, `2001-10-22` |
| **Notes** |  |

**Comment by rondlg** [comment]
deprecated - using temporalCoverage Class
