### ISSUE TITLE
Property:establishmentMeans

### ISSUE THREAD

**Issue by mswoodburn** [tdwg/cd#303]
|  |  |
| ---- | ---- |
| **Label** | Establishment Means |
| **Definition** | Statement about whether an organism or organisms have been introduced to a given place and time through the direct or indirect activity of modern humans. |
| **Usage** |  |
| **Existing property** | dwc:establishmentMeans |
| **Existing class** | dwc:Occurrence |
| **Existing property identifier** | http://rs.tdwg.org/dwc/terms/establishmentMeans |
| **Format** | Text |
| **Required** | No |
| **Repeatable** |  |
| **Constraints** |  |
| **Examples** | `native`, `nativeReintroduced`, `introduced`, `introducedAssistedColonisation`, `vagrant`, `uncertain` |
| **Notes** | Recommended best practice is to use controlled value strings from the controlled vocabulary designated for use with this term, listed at http://rs.tdwg.org/dwc/doc/em/. For details, refer to https://doi.org/10.3897/biss.3.38084 |

**Comment by fmjjones** [comment]
We have decided that this is not necessary at the Collection Description level.
