### ISSUE TITLE
SKOS mapping exercise for borrowed terms

### ISSUE THREAD

**Issue by essvee** [tdwg/cd#372]
**Notes from review meeting:** [2022-07-28](https://docs.google.com/document/d/16RCOisUhdl3h9ZmV2tZFHaRxnzdSfKbQKXKEaFKFAdA/edit#bookmark=id.8kbcy0om2g6j)  

Conduct a mapping exercise for each of  the [72 terms we've borrowed from another namespace](https://raw.githubusercontent.com/tdwg/cd/master/standard/terms/ltc_standard_terms_draft.csv) and update the terms accordingly.  

For each borrowed term in the termlist, we need to: 
1. Determine and record the nature of the match using SKOS vocab + syntax (egs under the link below and in the meetng notes)
2. Update the namespace field in the LtC termlist to 'ltc:' if the SKOS mapping is anything other `exact` or `narrow`

SKOS doc examples: https://www.w3.org/TR/skos-reference/#L4316

**Comment by mswoodburn** [comment]
Carrying out this exercise in the google sheet here: https://docs.google.com/spreadsheets/d/1w8DMgUwl7tf-9AXQOpT6IRQeMuUbxUZlJwQinrtUvAs/edit#gid=307972619

Complete (with various queries and possible actions required) for the borrowed terms, continuing the exercise for the ltc: terms to provide a broader picture of mappings between LtC and the other standards.
