### ISSUE TITLE
Outline the review-change process

### ISSUE THREAD

**Issue by essvee** [tdwg/cd#375]
**Notes from review meeting:** [2022-07-28](https://docs.google.com/document/d/16RCOisUhdl3h9ZmV2tZFHaRxnzdSfKbQKXKEaFKFAdA/edit#bookmark=id.8kbcy0om2g6j)

We need to nail down how we're going to use github to implement review suggestions, communicate these changes to the review team and leave an audit trail of changes made during this stage of the review. Process for the repo docs (termlist, etc) will differ to the wiki, but simpler is gooder. 

Already decided/discussed: 
- after each review, log issues for changes required, tag with the 'review' label and add to the 'Review tasks' project
- create 'review' branch for repo files and push any changes there
- for changes to the termlist, update the [csv](https://github.com/tdwg/cd/blob/master/standard/terms/ltc_standard_terms_draft.csv) rather than each individual issue, because it's quicker.
- for changes to the wiki, make sure to use the 'edit message' to describe roughly what has changed/why and use the footer. 
- when a change has been made, close the issue and reference the github commit or wiki version showing the end change.

**Comment by essvee** [comment]
I've made a review branch: https://github.com/tdwg/cd/tree/review 🌳

**Comment by rondlg** [comment]
### When the review phase is complete:

1. Merge the review branch back in the master
2. Update the wiki footer to include the version information.
3. Create a pdf of the wiki and upload it to the files section. Naming convention: LtC_wiki_v[number]. Add the link to this file into the footer.

**Comment by rondlg** [comment]
Updated Jutta's changes page to be a [Release Notes]([https://github.com/tdwg/cd/wiki/7.-Release-Notes) page.

**Comment by rondlg** [comment]
### Before you start the review.


1. Create a pdf of the wiki and upload it to the files section of the master branch.. Naming convention: LtC_wiki_v[number]. Add the link to this file into the footer. Note that all branches share the wiki section of the repo, so you should do this first!
2. Create a new “review” branch. Work here until the review phase is complete. 

- **Reviewer suggestions/recommendations (issues)**
- Create new issues as needed
- Document any discussion about suggestion/recommendation in the issue.

- **Term updates (issues)**
- Document any discussion about proposed changes to a particular term in its issue. Once a final decision is made update the term definition in the issue AND also in the [csv in the review repo](https://github.com/tdwg/cd/blob/review/standard/terms/ltc_standard_terms_draft.csv) NOT in the googlesheet version.

### When the review phase is complete

1. Merge the review branch back in the master

**Comment by mswoodburn** [comment]
@rondlg et al - turns out that it's also to create a local clone of the wiki (https://docs.github.com/en/communities/documenting-your-project-with-wikis/adding-or-editing-wiki-pages#cloning-wikis-to-your-computer), so I've done that and copied the md files for v1 into a wiki_archive folder in the main repo (master branch): https://github.com/tdwg/cd/tree/master/standard/wiki_archive. I also moved the pdf version to there from the repo root folder.
