### ISSUE TITLE
Fix Identifier.identifier

### ISSUE THREAD

**Issue by essvee** [tdwg/cd#377]
**Notes from review meeting:** [2022-07-28](https://docs.google.com/document/d/16RCOisUhdl3h9ZmV2tZFHaRxnzdSfKbQKXKEaFKFAdA/edit#bookmark=id.8kbcy0om2g6j)

[ltc:Identifier.identifier](https://github.com/tdwg/cd/issues/129) is currently mapped to dcterms:identifier, but it shouldn't be. We need to update it to work in the same way as [ContactDetail and ContactDetail.contactDetailValue](https://github.com/tdwg/cd/issues?q=is%3Aopen+is%3Aissue+label%3AClass%3AContactDetail)
- change the property name to identifierValue to make it less confusing
- remove/change the mapping to the dc: term (may need to be done in coordination with issue #372). 
 
Probably best to do this one in both the issue and the termlist csv, once we've got a review branch set up?

**Comment by jbstatgen** [comment]
Change of term name to Identifier.identifierValue - DONE
Added info to new wiki page https://github.com/tdwg/cd/wiki/Changes-during-review

The mapping question is still open.

**Comment by essvee** [comment]
Closing - PR #384. Mapping should be handled as part of #372

**Comment by jbstatgen** [comment]
Finally, done.
