### ISSUE TITLE
Fix broken link in the wiki

### ISSUE THREAD

**Issue by essvee** [tdwg/cd#378]
**Notes from review meeting:** [2022-07-28](https://docs.google.com/document/d/16RCOisUhdl3h9ZmV2tZFHaRxnzdSfKbQKXKEaFKFAdA/edit#bookmark=id.8kbcy0om2g6j)

Fix broken link in section 5. of the wiki (current version at time of logging: [f22c42d](https://github.com/tdwg/cd/wiki/5.-Reference-examples-and-implementations/f22c42dd02d23939cc73b1ce731c349489efce43)). When closing this issue, ref the version of the wiki where it's fixed. 

Broken link: https://latimer-core.wiki.opencura.com/

**Comment by mtrekels** [comment]
The Wikibase instance recently moved to Wikimedia infrastructure:

https://latimer-core.wikibase.cloud/

**Comment by mtrekels** [comment]
There are still a few issues with the move (old links should eventually redirect to the new location), and the search functionality might be running in a degraded mode.

**Comment by mtrekels** [comment]
@essvee do I need to change anything?

**Comment by essvee** [comment]
Aha! Thanks @mtrekels, no worries I'll update the docs w the new address 🐙 💻

**Comment by essvee** [comment]
Fixed in revision [4d4c02b](https://github.com/tdwg/cd/wiki/5.-Reference-examples-and-implementations/4d4c02b8dbcde054b0b4e51bde2e42c5e5581453)
