### ISSUE TITLE
Add one-page summary to wiki/docs

### ISSUE THREAD

**Issue by essvee** [tdwg/cd#380]
**Notes from review meeting:** [2022-07-28](https://docs.google.com/document/d/16RCOisUhdl3h9ZmV2tZFHaRxnzdSfKbQKXKEaFKFAdA/edit#bookmark=id.8kbcy0om2g6j)

Executive summary/one-pager/elevator pitch. There's probably text that can be pulled out from the existing docs for the basis of this: https://github.com/tdwg/cd/blob/master/standard/

**Comment by debpaul** [comment]
@essvee I wonder if a key graphic might be useful / enticing in this one-pager? (One of the models images that Matt made? Or?)

**Comment by magpiedin** [comment]
Added/done here - https://github.com/tdwg/cd/wiki 
(specifically this version for now - https://github.com/tdwg/cd/wiki/Home/5423d285d3088ce64cae5159d40ce191cb95e26b)
