### ISSUE TITLE
Add a page/section listing presentations given about LtC.

### ISSUE THREAD

**Issue by rondlg** [tdwg/cd#385]
Would be good to include links to presentations/publications about the LtC.

**Comment by magpiedin** [comment]
here's a starter list in the wiki / please add/edit as needed:

https://github.com/tdwg/cd/wiki/8.-Presentations-&-Publications

**Comment by jbstatgen** [comment]
and another one from the GBIF CESP workshop series:

[https://drive.google.com/file/d/1cFC6OWf_dLSvAgvattQMIr6QS_4FIX2T/view?usp=share_link](https://drive.google.com/file/d/1cFC6OWf_dLSvAgvattQMIr6QS_4FIX2T/view?usp=share_link)

**Comment by rondlg** [comment]
CESP presentation is added to the v2 wiki draft for transfer prior to public review. Closing this issue.
