### ISSUE TITLE
Recommendation for representing the data type of the items within an array in the term data type definition

### ISSUE THREAD

**Issue by mswoodburn** [tdwg/cd#396]

**Comment by rondlg** [comment]
Arrays. Need to make naming consistent. 

DECISION: 

**There are two kinds of Array:**

1. Complex arrays
> Complex array names should NOT be pluralized.
> Arrays with “has” at the beginning of the name indicate that the contents are instances of classes, serialized as JSON objects
> Reasoning: If array name points to a class (e.g. hasIdentifier) remain singular to maintain relationship to class.

2. Simple Arrays 
> Simple Array term names should be 
> While pluralizing simple arrays may help human-developers, we trust the ‘data type’ documentation 
> Arrays without a “has” indicate that it contains terms [a single simple data type, e.g. all strings, all numbers, etc.]. 

**Boolean values**

- Naming convention is to have “is” as a prefix e.g. ‘extinct’ vs ‘isExtinct’

**Comment by essvee** [comment]
Can this issue be closed now that a decision has been made? I've opened a new issue for the bool-type terms, which are the only ones which'll need changing.

**Comment by ben-norton** [comment]
Give me until COB Monday.

Ben Norton
Head of Technology
Collections Data Curator
Collections Manager of Mineralogy
Research & Collections
North Carolina Museum of Natural Sciences
https://orcid.org/0000-0002-5819-9134
https://naturalsciences.org/staff/ben-norton
***@***.******@***.***>
919.707.9947 (office)
520.241.8215 (cell)
________________________________
From: Sarah Vincent ***@***.***>
Sent: Thursday, October 27, 2022 12:43 PM
To: tdwg/cd
Cc: Norton, Ben; Assign
Subject: [External] Re: [tdwg/cd] Recommendation for representing the data type of the items within an array in the term data type definition (Issue #396)

CAUTION: External email. Do not click links or open attachments unless you verify. Send all suspicious email as an attachment to Report ***@***.***>


Can this issue be closed now that a decision has been made? I've opened a new issue for the bool-type terms, which are the only ones which'll need changing.

**Comment by essvee** [comment]
Oh no rush, sorry didn't mean to hassle you - I thought that Sharon's post was the conclusion of this issue so we didn't need the issue open any more, I do love ticking stuff off a to-do list, but I will restrain myself in this instance 😉

**Comment by ben-norton** [comment]
No problem. I need to walk through everything and I'm a bit behind or at least not where I'd like to be at the moment.

Ben Norton
Head of Technology
Collections Data Curator
Collections Manager of Mineralogy
Research & Collections
North Carolina Museum of Natural Sciences
https://orcid.org/0000-0002-5819-9134
https://naturalsciences.org/staff/ben-norton
***@***.******@***.***>
919.707.9947 (office)
520.241.8215 (cell)
________________________________
From: Sarah Vincent ***@***.***>
Sent: Friday, October 28, 2022 9:35 AM
To: tdwg/cd
Cc: Norton, Ben; Assign
Subject: [External] Re: [tdwg/cd] Recommendation for representing the data type of the items within an array in the term data type definition (Issue #396)

CAUTION: External email. Do not click links or open attachments unless you verify. Send all suspicious email as an attachment to Report ***@***.***>


Oh no rush, sorry didn't mean to hassle you - I thought that Sharon's post was the conclusion of this issue so we didn't need the issue open any more, I do love ticking stuff off a to-do list, but I will restrain myself in this instance 😉
