### ISSUE TITLE
Incorporate new datatype field and SKOS mappings into termlist generation script

### ISSUE THREAD

**Issue by mswoodburn** [tdwg/cd#397]
Dependency on #388. Could also include new date_added and term_status fields (#394)?

**Comment by rondlg** [comment]
From 6 October working group call
- Create a separate csv file with the term iri and the data type (int, string, boolean, array etc.)
- Don’t have a template yet.
- Controlled vocab for the datatypes still has to go to the TAG for review ratification etc.
- Draft is here: https://data.naturalsciences.org/docs/0.1/specifications/data-types
- Difference between a format and a type
- Array properties need to be plural
- 
- SKOS mapping: exact match is a subtype of close match; it is transitive, while close match isn’t; mapping needs exact match
- Add uri to the SKOS csv
- 
- Datatypes and SKOS are NOT normative at this stage
-

**Comment by essvee** [comment]
Datatypes have been split out for properties (https://github.com/tdwg/cd/blob/review/standard/terms/ltc_datatypes.csv) and removed from the termlist file. I won't close this issue because there are a few other tasks rolled up into it.

**Comment by ben-norton** [comment]
All pending items have been resolved and integrated into the documentation workflow.
