### ISSUE TITLE
Final review of TG charter

### ISSUE THREAD

**Issue by mswoodburn** [tdwg/cd#4]

**Comment by baskaufs** [comment]
Just to confirm, is the TG charter document under review [this one](https://github.com/tdwg/cd/blob/master/charters/draft/charter_collection_descriptions_tg_DRAFT.md)?

**Comment by debpaul** [comment]
Yes Steve.

**Comment by debpaul** [comment]
@mswoodburn Please review - and what should name be? I believe all changes requested are now made.
we need to remove the word "draft" to something like
cd_tg_charter.md?

**Comment by debpaul** [comment]
closing this ticket
