### ISSUE TITLE
Re-assess GeoOrigin terms for inclusion in first draft

### ISSUE THREAD

**Issue by essvee** [tdwg/cd#425]
I would think that Countries and States would be more useful than continent in a collection description (especially for those that are more specific than "global"). I'm surprised they are not options under this class.

_Originally posted by @Jegelewicz in https://github.com/tdwg/cd/issues/131#issuecomment-1302454913_

**Comment by rondlg** [comment]
See #141 and #142

**Comment by jbstatgen** [comment]
Better late than never ... 

On Tab "Registry_openDA_collection" of the "[Registry_Vocabularies](https://docs.google.com/spreadsheets/d/12D6P4lt-zDAALJzod7sq475tWgqKiTbDrFjKEuSXVg4/edit?usp=sharing)" spreadsheet file you can find the "Geographic region" schema from the [SYNTHESYS+ report](https://www.synthesys.info/content/dam/nhm-synthesys/synthesys-plus-deliverables/SYNTHESYS+%20D2.2%20Joint%20dashboard%20of%20collections%20assessment%20tools%20Final.pdf) (Tilley 2019) for the Collection Digitization Dashboard.

As a first guess,
Level 1 (aka 'GeographicSphere' by me) :=  missing in ltc:GeographicOrigin 
Level 2 (GeographicCategory) := ltc:continent (mmh, scale also required for oceans ...)
Level 3 (GeographicSubcategory):= ltc:region (here: SYNTHESYS+ provides only subdivisions in the Atlantic and Pacific)

**Comment by essvee** [comment]
Partially addressed by PR #428, but I'm leaving it open until someone reminds me whether ecoRegion (#225) is included or not - the ecoRegion term-level issue isn't tagged with 'done' so it might need another look. 

Will break out the renaming of stateProvince and county as flagged by @rondlg into another issue and make any ensuing changes separately to keep things simpler and easier to trace.

**Comment by essvee** [comment]
Working Group decision following discussion: Include ecoRegion in first draft, see notes from [30/11/2022](https://docs.google.com/document/d/16RCOisUhdl3h9ZmV2tZFHaRxnzdSfKbQKXKEaFKFAdA/edit#bookmark=id.6olb7lua69x1)
