### ISSUE TITLE
Updates to JSON schema files

### ISSUE THREAD

**Issue by jbstatgen** [tdwg/cd#427]
This is the issue to note and assemble suggestions for updates to the [JSON schema files](https://github.com/tdwg/cd/tree/review/standard/json-schema).

**Comment by essvee** [comment]
Fixed in [this commit](https://github.com/tdwg/cd/commit/4e88c0fd264e9f864507fc610ddd0ced02708dea), thanks for flagging @jbstatgen!

**Comment by jbstatgen** [comment]
@essvee another potential catch:

In `ltc:ObjectGroup`, we added `alternativeCollectionName`, however, I don't think it should be `required`. Though currently it is, or at least it is in the JSON file in the review branch.

Can you please have a look and update and/or let me know?

Thanks!

**Comment by essvee** [comment]
Made a separate issue (#452) for the required/repeatable issue flagged, so closing this one.
