### ISSUE TITLE
Rename CollectionDescriptionScheme class to LatimerCoreScheme

### ISSUE THREAD

**Issue by mswoodburn** [tdwg/cd#429]
Updates required:

1. term CSVs
    - [x]  [ltc_categories.csv](https://github.com/tdwg/cd/blob/review/standard/terms/ltc_categories.csv)
    - [x]  [ltc_datatypes.csv](https://github.com/tdwg/cd/blob/review/standard/terms/ltc_datatypes.csv)
    - [x]  [ltc_skos_mapping.csv](https://github.com/tdwg/cd/blob/review/standard/terms/ltc_skos_mapping.csv)
    - [x]  [ltc_standard_terms_draft.csv](https://github.com/tdwg/cd/blob/review/standard/terms/ltc_standard_terms_draft.csv)
    - [x] [by namespace](https://github.com/tdwg/cd/tree/review/standard/terms/by_namespace)
3. normative documentation
    - [x] [landing_page.md](https://github.com/tdwg/cd/blob/review/standard/landing_page.md)
    - [x] [termlist-header.md](https://github.com/tdwg/cd/blob/review/standard/termlist-header.md)
    - [ ] ? ["data_model" readme + definition docs?](https://github.com/tdwg/cd/tree/review/standard/data_model) ?
5. wiki (fairly widespread)
    - [ ] [wiki search for "CollectionDescriptionScheme"](https://github.com/tdwg/cd/search?q=collectiondescriptionscheme&type=wikis)
    - [ ] [wiki search for "Collection Description Scheme"](https://github.com/tdwg/cd/search?q=%22collection+description+scheme%22&type=wikis)
7. wiki diagrams
    - [ ] - [Wiki Home - Overview](https://github.com/tdwg/cd/wiki#1-overview-of-latimer-core)
    - [ ] - check other wiki-pages
9. JSON Schemas and JSON/CSV examples
    - [ ] - [main class](https://github.com/tdwg/cd/blob/review/standard/json-schema/collection-description-scheme.json)
    - [ ] - classes related via range or class-level properties

**Comment by magpiedin** [comment]
holding off from editing the following (for reason noted)

- ["data_model" readme + definition docs](https://github.com/tdwg/cd/tree/review/standard/data_model) (these appear to be docs that will/should be autogenerated &/or replaced by website when it's up)
- wiki searches + manual checks (pending reviewer edits/changes)
- JSON schema (https://github.com/tdwg/cd/blob/review/standard/json-schema/object-group.json) (to be autogenerated from the updated [terms CSVs](https://github.com/tdwg/cd/blob/review/standard/terms)
