### ISSUE TITLE
GeologicalContext.stratigraphyQualifier - new property to be added

### ISSUE THREAD

**Issue by essvee** [tdwg/cd#436]
See review session notes from [19th Jan, 2023](https://docs.google.com/document/d/16RCOisUhdl3h9ZmV2tZFHaRxnzdSfKbQKXKEaFKFAdA/edit#bookmark=id.z3kubhcw2pzd)

Rationale: Some geocontext names (formation, group, bed, member) aren't unique and geography is commonly use to disambiguate them. Ben and Ian are going to suggest a definition and a few examples. 
- Not mandatory, although you'd assume it would be commonly made so if one of (formation, supergroup, group, bed, member) was present.
- Not repeatable
- Format: String
- No mappings to existing terms identified

**Comment by ben-norton** [comment]
I think you can drop the term geographic. That level of specificity isn't as important as the function of the term itself.  
The qualifier eliminates the ambiguity in stratigraphic names resulting from discontinuities in stratigraphic nomenclature that commonly occur across administrative boundaries. An administrative division name is a sufficient qualifier in most cases, but a formal citation is acceptable and sufficient that the ambiguity is removed.

**Comment by ianengelbrecht** [comment]
Is this the topic we're going to discuss at paleo happy hour 9th March?

**Comment by essvee** [comment]
Yes please! 🐱‍🐉 The main things we're after are... 
- term name
- definition 
- confirmation that an equivalent term doesn't exist in another standard/a pointer towards one if it does

**Comment by essvee** [comment]
Closing - on consultation with the wider community, this term is not widely wanted. See notes from [12th April](https://docs.google.com/document/d/16RCOisUhdl3h9ZmV2tZFHaRxnzdSfKbQKXKEaFKFAdA/edit#bookmark=id.gv98bmo3sy0s)
