### ISSUE TITLE
GeologicalContext.superGroup - new property to be added

### ISSUE THREAD

**Issue by essvee** [tdwg/cd#438]
See review session notes from [19th Jan, 2023](https://docs.google.com/document/d/16RCOisUhdl3h9ZmV2tZFHaRxnzdSfKbQKXKEaFKFAdA/edit#bookmark=id.z3kubhcw2pzd)

Rationale: This term has been suggested as an addition to DwC (see https://github.com/tdwg/dwc/issues/234). It sounds like a handy level for collection-level records and is already used in several systems/datastores. 

- Suggested definition (taken from the [NASC](https://ngmdb.usgs.gov/Geolex/resources/docs/NACSN_Code_2021.pdf)): A supergroup is a formal assemblage of related or superposed groups, or of groups and formations. Such units have proved useful in regional and provincial syntheses. Supergroups should be named only where their recognition serves a clear purpose.
- Required: no
- Repeatable within a GC class: no

**Comment by JessUtrup** [comment]
Supergroups are commonly used in Europe, Asia, and Africa more than North America. Supergroups are also often used in rocks that predate the Phanerozoic, and as techniques advance more paleontological collections will end up with bacterial fossils and chemical traces of bacteria.

**Comment by christinajbyrd88** [comment]
The United States has some supergroups that postdate the Phanerozoic as well. While less commonly used in the US than the aforementioned countries, the US supergroups are highly fossiliferous and well sampled.

**Comment by rondlg** [comment]
New issues created for this term https://github.com/tdwg/cd/issues/479.

Pending review and sign off by working group.
