### ISSUE TITLE
Update linked properties `SchemeTerm` and `SchemeMeasurementOrFact` to `has...`

### ISSUE THREAD

**Issue by jbstatgen** [tdwg/cd#443]
In the `CollectionDescriptionScheme`/`ObjectGroupCollectionScheme` class update the properties

- `SchemeTerm` to `hasSchemeTerm` and
- `SchemeMeasurementOrFact` to `hasSchemeMeasurementOrFact`

**Comment by essvee** [comment]
This looks like it's already been done on review (see link), so I'm going to close this issue. If I've missed/misunderstood something, please re-open and specify where you've seen the old names persisting, thanks! 

https://github.com/tdwg/cd/blob/review/standard/json-schema/collection-description-scheme.json#L39
