### ISSUE TITLE
Provide examples for Property:chronometricAgeProtocol

### ISSUE THREAD

**Issue by ben-norton** [tdwg/cd#445]
Provide examples for the Property:chronometricAgeProtocol http://rs.tdwg.org/chrono/terms/chronometricAgeProtocol with the intent to replace the current set (1510 +/- 25 14C yr BP, 16.26 Ma +/- 0.016)

**Comment by ben-norton** [comment]
Radiocarbon dating using an Accelerator Mass Spectrometry
Pb-Pb Dating
41Ca - 41K Chronometer
U-Pb Dating using a Thermal Ionization Mass Spectrometer  
U-Pb Radiometric Dating
Thermoluminescence
Paleomagnetism
Pb-Pb Chronometer as described in Amelin et al. (2002) Science 297, 1678-1683.

**Comment by essvee** [comment]
Closed by #480
