### ISSUE TITLE
Check if required property is resourceID or shouldn't be relatedResourceID

### ISSUE THREAD

**Issue by jbstatgen** [tdwg/cd#447]
https://github.com/tdwg/cd/blob/ac90d89854441f1513b1e7eada987ddeebdc5fa8/standard/json-schema/resource-relationship.json#L79

The required property for the `ltc:ResourceRelationship` class might not be `resourceID` as set currently, but rather `relatedResourceID`.

**Comment by essvee** [comment]
Just to clarify: this issue relates to the definition of the class/properties, not the way it's describe in the json-schema files. 

I'm not sure if we ever discussed this one in the working group and I can't find anything in the notes.  Flagging it as a question to pick up in the next meeting so we can decide whether or not we need to update in the post-review purge.

**Comment by essvee** [comment]
Discussed at 31st MArch working group meeting ([see notes](https://docs.google.com/document/d/16RCOisUhdl3h9ZmV2tZFHaRxnzdSfKbQKXKEaFKFAdA/edit#bookmark=id.c75610scr99k)) - decided to leave as-is, so closing this issue as resolved.
