### ISSUE TITLE
CollectionStatusHistory.statusType - update notes field

### ISSUE THREAD

**Issue by essvee** [tdwg/cd#450]
See meeting notes: [9th Feb 23](https://docs.google.com/document/d/16RCOisUhdl3h9ZmV2tZFHaRxnzdSfKbQKXKEaFKFAdA/edit#bookmark=id.2xvzc9fwhuii)
Original def: #367 
Current master def: [ltc_standard_terms_draft.csv](https://github.com/tdwg/cd/blob/review/standard/terms/ltc_standard_terms_draft.csv)

Add to the notes field for this term that 'Recommended best practice is to use a controlled vocabulary.' (choice of vocab is an implementation issue)

**Comment by fmjjones** [comment]
Updated notes to include: Recommended best practice is to use a controlled vocabulary.
