### ISSUE TITLE
CollectionStatusHistory.statusChangeReason - add example for SpatialCoverage change

### ISSUE THREAD

**Issue by essvee** [tdwg/cd#451]
See meeting notes: [9th Feb 23](https://docs.google.com/document/d/16RCOisUhdl3h9ZmV2tZFHaRxnzdSfKbQKXKEaFKFAdA/edit#bookmark=id.2xvzc9fwhuii)
Original def: #124 
Current master def: [ltc_standard_terms_draft.csv](https://github.com/tdwg/cd/blob/review/standard/terms/ltc_standard_terms_draft.csv)

The notes for this meeting say 'Add example for SpatialCoverage change (similar to TemporalCoverage)', but we might need to clarify what that means because I can't remember. Is it about the collection moving to a new org/storage location, which has impacted accessibility for loans/visits?

**Comment by essvee** [comment]
Clarification on changes reqauired (See [March 31st Meeting notes](https://docs.google.com/document/d/16RCOisUhdl3h9ZmV2tZFHaRxnzdSfKbQKXKEaFKFAdA/edit#bookmark=id.c75610scr99k)

This (“spatial coverage change”) refers to moving an object group to a different place NOT a different institution.
So it is not accessible at the original location
The example we need to add to this class is about a change in a collection status that is caused by the relocation of a collection within an institution (not between institutions). For example, a collection that was previously accessible to visitors, but is no longer because it’s moved to a secure offsite store. OR, the collection was in the process of being moved in the years 2000-2001, so no-one can access it during that time.

**Comment by jbstatgen** [comment]
`moved to secure off-site storage`, `reorganization, no access from 2020-2023`
