### ISSUE TITLE
Reference.referenceName - update term name, examples, skos mapping + definition

### ISSUE THREAD

**Issue by essvee** [tdwg/cd#453]
See meeting notes: [2nd March 23](https://docs.google.com/document/d/16RCOisUhdl3h9ZmV2tZFHaRxnzdSfKbQKXKEaFKFAdA/edit#bookmark=id.ffnvjzo8co13), [12th April](https://docs.google.com/document/d/16RCOisUhdl3h9ZmV2tZFHaRxnzdSfKbQKXKEaFKFAdA/edit#bookmark=id.gv98bmo3sy0s)
Original def: https://github.com/tdwg/cd/issues/325
Master def: https://github.com/tdwg/cd/blob/review/standard/terms/ltc_standard_terms_draft.csv#L191
Has SKOS Mapping: https://github.com/tdwg/cd/blob/review/standard/terms/ltc_skos_mapping.csv#L121

It's unclear which field should be used for the title of a reference at the moment - referenceText or referenceDetails (former is correct: latter is for full citation string, or any unstructured comments/clarifying text). We need to update the property title and definition to make this clearer:

* [x] Change the property name from `referenceText` to `referenceName`
* [x] Change definition to 'A name given to a reference'
* [x] Add an example of a paper/monograph title
* [x] Add note that  ‘If the reference is to a publication, this field should hold the publication title; otherwise any appropriate, short, text label relevant to the resource being referenced may be used.’
* [x] Update the SKOS mapping so this term is a narrowMatch to dc:title (http://purl.org/dc/terms/title), rather than a closeMatch to abcd:text

**Comment by mswoodburn** [comment]
Closed as complete
