### ISSUE TITLE
Reference.referenceDetails - update examples

### ISSUE THREAD

**Issue by essvee** [tdwg/cd#454]
See meeting notes: [2nd March 23](https://docs.google.com/document/d/16RCOisUhdl3h9ZmV2tZFHaRxnzdSfKbQKXKEaFKFAdA/edit#bookmark=id.ffnvjzo8co13)
Original def: https://github.com/tdwg/cd/issues/326
Current master def: https://github.com/tdwg/cd/blob/review/standard/terms/ltc_standard_terms_draft.csv#L190

* [ ] Add a full bibliographic citation string or two to the list of examples.

**Comment by jbstatgen** [comment]
`de Mestier A, Mulcahy D, Harris DJ, et al. (2023) Policies Handbook on Using Molecular Collections. Research Ideas and Outcomes 9: e102908. https://doi.org/10.3897/rio.9.e102908` `Suggested citation: USDA-ARS US National Fungus Collection (2023). USDA United States National Fungus Collections. Occurrence dataset https://doi.org/10.15468/w78rwb accessed via GBIF.org on 2023-04-27.`
