### ISSUE TITLE
ltc:Role - new class to be added

### ISSUE THREAD

**Issue by essvee** [tdwg/cd#464]
See meeting notes: [2nd March 23](https://docs.google.com/document/d/16RCOisUhdl3h9ZmV2tZFHaRxnzdSfKbQKXKEaFKFAdA/edit#bookmark=id.ffnvjzo8co13)

Adding a separate, bare-bones, role class was recommended by the reviewer team after working through the PersonRole/Person classes, partially because it allows us to be able to tag a role (separate to the peron or persons performing it) with an identifier, which could be handy if you wanted a way to refer to an external controlled vocab/ontology. 

* [x] Add new class-level term ltc:Role (we don't ahve a suggested def/any mappigns to external terms for this afaik)
* [ ] Add Role properties: 
  * [x] Role.roleName (string, not mandatory, not repeatable)
  * [x] Role.hasIdentifier (array, not mandatory, repeatable)
  * [ ] ~Role.hasFunction (string, not mandatory, not repeatable)~
* [x] Delete old PersonRole.role property
* [x] Add PersonRole.hasRole property (array, not mandatory, repeatable)  
* [x] Edit PersonRole class description/notes to recommend that, if you use this class, you should have at least hasPerson or hasRole populated.

**Comment by mswoodburn** [comment]
As the role is being broken out into a separate class, it might be clearer to rename PersonRole to e.g. PersonAttribution? Would also align better with the terminology for linking between agent and entity in PROV (https://www.w3.org/TR/prov-o/#wasAttributedTo).

**Comment by jbstatgen** [comment]
Mmh, there is also the relationship between a Person and an Activity: `wasAssociatedWith` ([https://www.w3.org/TR/prov-o/#wasAssociatedWith](https://www.w3.org/TR/prov-o/#wasAssociatedWith)).
Will it be sensible to distinguish these two types?

**Comment by mswoodburn** [comment]
Changes made, apart from the hasFunction property - not sure what that was meant to be, and don't think featured when we reviewed the issue last week?

**Comment by essvee** [comment]
> Changes made, apart from the hasFunction property - not sure what that was meant to be, and don't think featured when we reviewed the issue last week?

Yeahhh so apparently I added that in during the last meeting and I've no idea why - it shouldn't be a 'has...' for a string anyway. I reckon ignore and if it comes up again we can change it.
