### ISSUE TITLE
ResourceRelationship.relatedResourceID - update usage notes

### ISSUE THREAD

**Issue by essvee** [tdwg/cd#472]
See meeting notes from [March 31st 23](https://docs.google.com/document/d/16RCOisUhdl3h9ZmV2tZFHaRxnzdSfKbQKXKEaFKFAdA/edit#bookmark=id.c75610scr99k)

* [ ] Update the notes to make it clear that this term should be a PID for the objectgroup or recordLevel class is a property of.

**Comment by mswoodburn** [comment]
This seems reasonably clear already, so closing issue
