### ISSUE TITLE
Distinguish 'object group'- vs 'collection'-specific terms

### ISSUE THREAD

**Issue by magpiedin** [tdwg/cd#476]
- [x] #477 
- [x] #478
- [x] #429
- [ ] create table in wiki that divides terms into Human vs Machine-readable terms

See notes from [13 April 2023](https://docs.google.com/document/d/16RCOisUhdl3h9ZmV2tZFHaRxnzdSfKbQKXKEaFKFAdA/edit#heading=h.ra4n3ebg1un5)

**Comment by rondlg** [comment]
Note: The distinguishing point here is that the term is intended to help in a machine readable context rather than something more helpful for humans to read.

**Comment by fmjjones** [comment]
The csv in the review branch https://github.com/tdwg/cd/blob/review/reference/humanVmachine.md.
