### ISSUE TITLE
Property:recordCreator

### ISSUE THREAD

**Issue by mtrekels** [tdwg/cd#49]
|  |  |
| ---- | ---- |
| **Label** |  |
| **Definition** | An entity responsible for making the resource. |
| **Usage** | An entity responsible for making the collection description record. |
| **Existing property** | dc:creator |
| **Existing class** |  |
| **Existing property identifier** | http://purl.org/dc/terms/creator |
| **Format** | URI |
| **Required** | no |
| **Repeatable** | yes |
| **Constraints** |  |
| **Examples** | `Smith, Clare` `Natural History Museum, London` `https://orcid.org/XXXX-XXXX-XXXX-XXXX` `https://ror.org/XXaaaXXXX` |
| **Notes** | Recommended practice is to identify the creator with a URI. If this is not possible or feasible, a literal value that identifies the creator may be provided. Equivalent property: http://xmlns.com/foaf/0.1/maker. This value would not change. Record the entity that updated the record in the Editor field. |

**Comment by mswoodburn** [comment]
Deprecated in favour of the generic Person and PersonRole classes and properties
