### ISSUE TITLE
Check and update SKOS mappings

### ISSUE THREAD

**Issue by essvee** [tdwg/cd#490]
As part of end-stage-review QC work (ref notes from [18th May 2023](https://docs.google.com/document/d/16RCOisUhdl3h9ZmV2tZFHaRxnzdSfKbQKXKEaFKFAdA/edit#bookmark=id.riswt1q9ebh9)

- [x] Check skos mappings in [ltc_skos_mapping.csv](https://github.com/tdwg/cd/blob/review/standard/terms/ltc_skos_mapping.csv) and update/remove/add where necessary
- [x] Replace names in skos mapping with URIs
- [x] Replace all the LtC terms in term_localName with URIs

**Comment by mswoodburn** [comment]
Done and updated ltc_skos_mapping.csv
