### ISSUE TITLE
Confirm presence and relevance of examples

### ISSUE THREAD

**Issue by essvee** [tdwg/cd#491]
Part of end-stage-review QC work (ref notes from [18th May 2023](https://docs.google.com/document/d/16RCOisUhdl3h9ZmV2tZFHaRxnzdSfKbQKXKEaFKFAdA/edit#bookmark=id.riswt1q9ebh9)).

Confirm that there are appropriate examples in place for every class and property listed in [ltc_standard_terms_draft.csv](https://github.com/tdwg/cd/blob/review/standard/terms/ltc_standard_terms_draft.csv), excluding any `ltc:hasFoo` terms because examples in that case are given under the `Foo` docs. Examples should be wrapped in backticks and comma-delimited. 
- [x] Address
- [x] Chronometric Age
- [x] Latimer Core Scheme
- [x] Collection Status History
- [x] Contact Detail
- [x] Event
- [x] Geographic Context
- [x] Geological Context
- [x] Identifier
- [x] Measurement or Fact
- [x] Object Classification
- [ ] Object Group
- [x] Organisational Unit
- [x] Person
- [x] Person Role
- [x] Record Level
- [x] Reference
- [x] Resource Relationship
- [x] Role
- [x] Scheme Measurement Or Fact
- [x] Scheme Term
- [x] Storage Location
- [x] Taxon
- [x] Temporal Coverage

**Comment by magpiedin** [comment]
Examples are now setup for most, and as new cases come up, we will add new examples
