### ISSUE TITLE
Property:recordCreatedDate

### ISSUE THREAD

**Issue by mtrekels** [tdwg/cd#51]
|  |  |
| ---- | ---- |
| **Label** |  |
| **Definition** | Date of creation of the resource. |
| **Usage** | A date or range of dates over which the collection description record was created. |
| **Existing property** | dcterms:created |
| **Existing class** |  |
| **Existing property identifier** | http://purl.org/dc/terms/created |
| **Format** | Text |
| **Required** | yes |
| **Repeatable** | no |
| **Constraints** |  |
| **Examples** | `1998-02-16` `1998-02` `1998` `2019-12-16T09:49:51Z` |
| **Notes** | Date may be used to express temporal information at any level of granularity. Recommended practice is to express the date, date/time, or period of time according to ISO 8601-1 [ISO 8601-1] or a published profile of the ISO standard, such as the W3C Note on Date and Time Formats [W3CDTF] or the Extended Date/Time Format Specification [EDTF]. If the full date is unknown, month and year (YYYY-MM) or just year (YYYY) may be used. Date ranges may be specified using ISO 8601 period of time specification in which start and end dates are separated by a '/' (slash) character. Either the start or end date may be missing. |

**Comment by mswoodburn** [comment]
Added dc:created definition, and notes from dc:date

**Comment by mswoodburn** [comment]
Deprecated in favour of the generic Person and PersonRole classes and properties
