### ISSUE TITLE
Property:recordEditor

### ISSUE THREAD

**Issue by mtrekels** [tdwg/cd#52]
|  |  |
| ---- | ---- |
| **Label** |  |
| **Definition** | An entity responsible for making contributions to the resource. |
| **Usage** | An entity responsible for making contributions to the collection description record. |
| **Existing property** | dc:contributor |
| **Existing class** |  |
| **Existing property identifier** | http://purl.org/dc/terms/contributor |
| **Format** | URI |
| **Required** | yes |
| **Repeatable** | yes |
| **Constraints** |  |
| **Examples** | `Smith, Clare` `Natural History Museum, London` `https://orcid.org/XXXX-XXXX-XXXX-XXXX` `https://ror.org/XXaaaXXXX` |
| **Notes** | Recommended practice is to identify the editor with a URI. If this is not possible or feasible, a literal value that identifies the editor may be provided. In the context of the CD data standard it is the last entity that edited the record. The entity that originally created the record should be recorded in the Creator field. |

**Comment by mtrekels** [comment]
|  |  |
| ---- | ---- |
| **Definition** | An entity responsible for making contributions to the resource. |
| **Dimension** |  |
| **Existing property** | dc:contributor |
| **Existing class** |  |
| **Existing property identifier** | http://purl.org/dc/elements/1.1/contributor |
| **Format** |  |
| **Required** | yes |
| **Repeatable** |  |
| **Constraints** |  |
| **Examples** |  |
| **Notes** | The guidelines for using names of persons or organizations as creators also apply to contributors. Typically, the name of a Contributor should be used to indicate the entity. In the context of CD it is the last Person that edited the record. |

**Comment by mswoodburn** [comment]
Moved the changes in to the header table, added some examples (same as 'creator'). I've also modified the notes so that the reader doesn't need to refer to the 'creator' property as well.

**Comment by mswoodburn** [comment]
Deprecated in favour of the generic Person and PersonRole classes and properties
