### ISSUE TITLE
Property:recordEditedDate

### ISSUE THREAD

**Issue by mtrekels** [tdwg/cd#53]
|  |  |
| ---- | ---- |
| **Label** |  |
| **Definition** | Date on which the resource was changed. |
| **Usage** | Date on which the Collection Description record was changed. |
| **Existing property** | dc:modified |
| **Existing class** |  |
| **Existing property identifier** | http://purl.org/dc/terms/modified |
| **Format** | Date |
| **Required** | yes |
| **Repeatable** | no |
| **Constraints** | ISO 8601 |
| **Examples** | `1998-02-16` `1998-02` `1998` `2019-12-16T09:49:51Z` |
| **Notes** | Date may be used to express temporal information at any level of granularity. Recommended practice is to express the date, date/time, or period of time according to ISO 8601-1 [ISO 8601-1] or a published profile of the ISO standard, such as the W3C Note on Date and Time Formats [W3CDTF] or the Extended Date/Time Format Specification [EDTF]. If the full date is unknown, month and year (YYYY-MM) or just year (YYYY) may be used. Date ranges may be specified using ISO 8601 period of time specification in which start and end dates are separated by a '/' (slash) character. Either the start or end date may be missing. |

**Comment by mtrekels** [comment]
|  |  |
| ---- | ---- |
| **Definition** | Date on which the resource was changed. |
| **Dimension** |  |
| **Existing property** | dc:modified |
| **Existing class** |  |
| **Existing property identifier** | http://purl.org/dc/terms/modified |
| **Format** |  |
| **Required** | yes |
| **Repeatable** |  |
| **Constraints** | ISO 8601 |
| **Examples** | 2019-12-16T09:49:51Z |
| **Notes** | Recommended practice is to describe the date, date/time, or period of time as recommended for the property Date, of which this is a subproperty. |

**Comment by mswoodburn** [comment]
Deprecated in favour of the generic Person and PersonRole classes and properties
