### ISSUE TITLE
Property:collectionDescriptionID

### ISSUE THREAD

**Issue by mtrekels** [tdwg/cd#56]
|  |  |
| ---- | ---- |
| **Definition** | Unique persistent identifier for the CollectionDescription |
| **Existing property** |  |
| **Existing class** |  |
| **Existing property identifier** |  |
| **Format** | Text |
| **Required** | Yes |
| **Repeatable** |  |
| **Constraints** | GUID? |
| **Examples** |  |
| **Notes** |  |

**Comment by wouteraddink** [comment]
This may be similar to a digital specimen identifier (NSId) for specimen, with the difference that there might quite often not be a physical collection identifier as compared to a specimen where there in principle always is one (usually attached as a barcode label) if a preserved specimen exists.

**Comment by mswoodburn** [comment]
Closing this issue, as we agreed that it's a duplication of the PID property
