### ISSUE TITLE
Property:onlineResources

### ISSUE THREAD

**Issue by mtrekels** [tdwg/cd#60]
|  |  |
| ---- | ---- |
| **Label** | Online Resources |
| **Definition** | Online presence (which portals hold information on the collection) |
| **Usage** |  |
| **Existing property** |  |
| **Existing class** |  |
| **Existing property identifier** |  |
| **Format** | List |
| **Required** |  |
| **Repeatable** | Yes |
| **Constraints** |  |
| **Examples** |  |
| **Notes** |  |

**Comment by falkogloeckler** [comment]
I don't understand why this would be of format "List".
Wouldn't that directly point to a landing page of the online presence as a URI or URL
(just like in ABCD the element "ProductURI", which is the URI that embeds a "MultimediaObject"

**Comment by mswoodburn** [comment]
The 'list' format I think was to support the possibility of > 1 resource URIs for a single CollectionDescription. Similar to the comments on the datasetDOIs property, might be something we want to break out into a separate class? And clarify how this differs from related datasets.

**Comment by mswoodburn** [comment]
Alternatively there's a suggestion from a comment in the index sheet that this could be covered by the Dublin Core cdl:isAccessedVia term: https://www.dublincore.org/specifications/dublin-core/collection-description/collection-application-profile/#colcldisAccessedVia

**Comment by mswoodburn** [comment]
DEPRECATED in favour of the generic Reference class
