### ISSUE TITLE
Property:collectionStrength

### ISSUE THREAD

**Issue by mtrekels** [tdwg/cd#63]
|  |  |
| ---- | ---- |
| **Label** | Collection Strength |
| **Definition** | A textual description of the strengths of the collection |
| **Usage** |  |
| **Existing property** |  |
| **Existing class** |  |
| **Existing property identifier** |  |
| **Format** | Text |
| **Required** |  |
| **Repeatable** | Yes |
| **Constraints** |  |
| **Examples** |  |
| **Notes** | Overlap with thematic focus? |

**Comment by CatChapman** [comment]
This seems a bit vague... strengths in what way? How the collection sets itself apart from others? Usefulness in research? Something else? Just seems pretty vague to have as an entire property, when it could be, as stated in the notes, considered overlapped with thematic focus... but I suppose this could be useful for really niche collections?

**Comment by fmjjones** [comment]
Agreed, issue #62  and this issue should be combined. Use the more general "collectionStrength" as it is more commonly used among collections.
