### ISSUE TITLE
Property:storageVolume

### ISSUE THREAD

**Issue by mtrekels** [tdwg/cd#73]
|  |  |
| ---- | ---- |
| **Definition** | Physical volume taken up by the collection in cubic meters. |
| **Existing property** |  |
| **Existing class** |  |
| **Existing property identifier** |  |
| **Format** | Numeric |
| **Required** |  |
| **Repeatable** | no |
| **Constraints** |  |
| **Examples** | 20 |
| **Notes** |  |

**Comment by mtrekels** [comment]
Proposal for definition: Physical volume taken up by the collection.

Examples: 20 m^3

**Comment by mswoodburn** [comment]
Deprecated in favour of MeasurementOrFact class
