### ISSUE TITLE
Property:storageVolumeUnit

### ISSUE THREAD

**Issue by mtrekels** [tdwg/cd#74]
|  |  |
| ---- | ---- |
| **Definition** |  |
| **Existing property** |  |
| **Existing class** |  |
| **Existing property identifier** |  |
| **Format** | Text |
| **Required** |  |
| **Repeatable** | no |
| **Constraints** | Controlled vocabulary |
| **Examples** |  |
| **Notes** |  |

**Comment by mtrekels** [comment]
What do we really want to measure here? Is number of shelves/jars/cupboards a good metric? Or do we want a physical volume?

A possible definition could be: Physical method of storage for the collection items within the collection footprint unit

Examples: number of shelves, number of jars, drawers

**Comment by mswoodburn** [comment]
I think we're looking at the numeric volume taken up by the collection here, e.g. in m^2. The 3D equivalent of the storageFootprint metric.

**Comment by mtrekels** [comment]
Proposal for definition: Unit of volume taken up by the collection.

Examples: m^3

**Comment by mswoodburn** [comment]
Deprecated in favour of MeasurementOrFact class
