### ISSUE TITLE
Property:storageVolumeConfidence

### ISSUE THREAD

**Issue by mtrekels** [tdwg/cd#75]
|  |  |
| ---- | ---- |
| **Definition** |  |
| **Existing property** |  |
| **Existing class** |  |
| **Existing property identifier** |  |
| **Format** | Percentage |
| **Required** |  |
| **Repeatable** | no |
| **Constraints** |  |
| **Examples** | 10% |
| **Notes** |  |

**Comment by mtrekels** [comment]
Proposal for definition: Confidence level on the estimation of volume taken up by the collection.

Side note: we give as an example '10%'. This means that we have a potential error of 10% on the estimated volume

This field should only be filled when the storageVolumeMethod == estimate, it becomes meaningless when the method is Exact Count

**Comment by mswoodburn** [comment]
Deprecated in favour of MeasurementOrFact class
