### ISSUE TITLE
Property:storageVolumeMethod

### ISSUE THREAD

**Issue by mtrekels** [tdwg/cd#76]
|  |  |
| ---- | ---- |
| **Definition** |  |
| **Existing property** |  |
| **Existing class** |  |
| **Existing property identifier** |  |
| **Format** | Text |
| **Required** |  |
| **Repeatable** | no |
| **Constraints** | Controlled vocabulary |
| **Examples** | Estimate; Precise count; Minimum; Maximum |
| **Notes** |  |

**Comment by mtrekels** [comment]
Proposed definition: Statistical metric metric/figure used to report the storage volume.

**Comment by mswoodburn** [comment]
Deprecated in favour of MeasurementOrFact class
