### ISSUE TITLE
Property:storageFootprintUnit

### ISSUE THREAD

**Issue by mtrekels** [tdwg/cd#78]
|  |  |
| ---- | ---- |
| **Definition** | The units used to express the storage footprint of the collection |
| **Existing property** |  |
| **Existing class** |  |
| **Existing property identifier** |  |
| **Format** | Text |
| **Required** | yes, if storageFootprint is populated |
| **Repeatable** | no |
| **Constraints** | Controlled vocabulary |
| **Examples** | m2, Square foot |
| **Notes** |  |

**Comment by mtrekels** [comment]
Definition: Unit used to express the footprint of the collection

Examples: m^2, ft^2

**Comment by mswoodburn** [comment]
Deprecated in favour of MeasurementOrFact class
