### ISSUE TITLE
Property:storageFootprintConfidence

### ISSUE THREAD

**Issue by mtrekels** [tdwg/cd#79]
|  |  |
| ---- | ---- |
| **Definition** | The percentage confidence in the estimate of the storage footprint |
| **Existing property** |  |
| **Existing class** |  |
| **Existing property identifier** |  |
| **Format** | Percentage |
| **Required** | no |
| **Repeatable** | no |
| **Constraints** |  |
| **Examples** | 5% |
| **Notes** |  |

**Comment by mtrekels** [comment]
Definition: Confidence level on the estimation of the floor area

**Comment by mswoodburn** [comment]
Deprecated in favour of MeasurementOrFact class
