### ISSUE TITLE
Property:storageFootprintMethod

### ISSUE THREAD

**Issue by mtrekels** [tdwg/cd#80]
|  |  |
| ---- | ---- |
| **Definition** | The method used to calculate or estimate the storage footprint |
| **Existing property** |  |
| **Existing class** |  |
| **Existing property identifier** |  |
| **Format** | Text |
| **Required** | yes, if storageFootprint is populated |
| **Repeatable** | no |
| **Constraints** | Controlled vocabulary |
| **Examples** | Estimate; Precise count; Minimum; Maximum |
| **Notes** |  |

**Comment by mtrekels** [comment]
Proposed definition: Statistical metric used to report the collection footprint

**Comment by mswoodburn** [comment]
Deprecated in favour of MeasurementOrFact class

**Comment by mswoodburn** [comment]
Deprecated in favour of MeasurementOrFact class
