### ISSUE TITLE
Class:ObjectQuantity

### ISSUE THREAD

**Issue by mtrekels** [tdwg/cd#81]
|  |  |
| ---- | ---- |
| **Parent** | ObjectGroup |
| **Definition** | Metric for recording counts or estimates of the quantity of objects described by the CollectionDescription. |
| **Repeatable** | Yes |
| **Relationships** |  |
| **Potential standards/vocabularies/ontologies to adopt** | |
| **Notes** | Should support multiple quantity metrics of different types for physical objects within the CollectionDescription. The objectType controlled vocabulary is key for constraining these definitions and making the figures interoperable between CollectionDescription records and schemes. |

**Comment by mswoodburn** [comment]
Changed the parent to ObjectGroup, due to removing the CollectionDescriptionMetric class

**Comment by mswoodburn** [comment]
Deprecated in favour of MeasurementOrFact class
