### ISSUE TITLE
Property:objectQuantityType

### ISSUE THREAD

**Issue by mtrekels** [tdwg/cd#82]
|  |  |
| ---- | ---- |
| **Definition** | The object being counted in objectQuantity. |
| **Existing property** |  |
| **Existing class** |  |
| **Existing property identifier** |  |
| **Format** | Text |
| **Required** | Yes |
| **Repeatable** | no |
| **Constraints** | This field is required when objectQuantity is populated.  |
| **Examples** | specimen; lot; draw; cupboard; cabinet |
| **Notes** | This is the description of  the "thing" that is counted in cd:objectQuantity to quantify a collection. However, it may not necessarily be the number of individual specimens in the collection.  |

**Comment by qgroom** [comment]
This term name doesn't make sense. The definition objectQuantityType is similar to objectType. Clearly this does not refer to a "type" of "objectQuantity", or does it?

**Comment by mswoodburn** [comment]
Deprecated in favour of MeasurementOrFact class
