### ISSUE TITLE
Property:objectQuantity

### ISSUE THREAD

**Issue by mtrekels** [tdwg/cd#83]
|  |  |
| ---- | ---- |
| **Definition** | The quantity of objects described by the CollectionDescription, as defined by the objectType. |
| **Existing property** |  |
| **Existing class** |  |
| **Existing property identifier** |  |
| **Format** | Integer |
| **Required** | Yes |
| **Repeatable** | Yes |
| **Constraints** | >=0 |
| **Examples** | 20000 |
| **Notes** | Type of object counted is defined by the ObjectType defined for the CollectionDescription e.g. jar, slide, whole organism |

**Comment by fmjjones** [comment]
For active collections this metric will be out of date almost as soon as it's entered. See also issue # 84. It might make sense to create a last date modified for this Class instead of or with a confidence field.

**Comment by qgroom** [comment]
recordEditedDate is available on the whole CD record to indicate when the metric is valid from.

**Comment by mswoodburn** [comment]
Deprecated in favour of MeasurementOrFact class
