### ISSUE TITLE
Property:objectQuantityConfidence

### ISSUE THREAD

**Issue by mtrekels** [tdwg/cd#84]
|  |  |
| ---- | ---- |
| **Definition** | A estimated margin of error on the object quantity. |
| **Existing property** |  |
| **Existing class** |  |
| **Existing property identifier** |  |
| **Format** | Percentage |
| **Required** | Yes |
| **Repeatable** | no |
| **Constraints** |  |
| **Examples** | 5% |
| **Notes** | If we estimate we have 100 specimens at a precision of 5%, then we actually estimate that there are between 95 and 105 specimens in the collection  |

**Comment by cp-weiland** [comment]
> estimate we have 100 specimens at a precision of 5%,
From my understanding, this is the percentage error, means the discrepancy between observed and true -> (V_observed - V_true)/V_true, here (105-100)/100 = 5%. Precision refers (from my understanding) to reproducebility and consistency of a series of values. So if we have a set of specimen, where 100 specimen are of class x but we classifiy 105 as x, then Precision = TruePositives/(TruePositives+FalsePositives) = 100/105 = .95...

**Comment by qgroom** [comment]
removed from notes 

> Application will be influenced by the objectQuantityMethod. The percentage is meant to define the precision to which the measure is made. Therefore, i

Updated definition

**Comment by mswoodburn** [comment]
Deprecated in favour of MeasurementOrFact class
