### ISSUE TITLE
Property:objectQuantityMethod

### ISSUE THREAD

**Issue by mtrekels** [tdwg/cd#85]
|  |  |
| ---- | ---- |
| **Definition** | The method used to count the objects represented by the CollectionDescription. |
| **Existing property** |  |
| **Existing class** |  |
| **Existing property identifier** |  |
| **Format** | Text |
| **Required** | Yes |
| **Repeatable** | no |
| **Constraints** | Controlled vocabulary |
| **Examples** | Estimate; Precise count; Minimum; Maximum |
| **Notes** |  |

**Comment by cp-weiland** [comment]
A precise count is from my understanding related to object classification: Example precise count: this is "classify and count" (classify each item in a set and count x_1, x_2 ... y_1, y_2 ... etc.). Considering quantification in the sense of estimation (mapping unlabelled objects to a set of classes x,y ... e.g, taxa) different evaluation measures might be considered. So maybe an additional property 'evaluatioMethod" or 'estimationMethod' is usefull, which is 'void' or 'defult# in case of 'clasify and count'?

**Comment by qgroom** [comment]
This was needed to aggregate number across collections. If the controlled vocabulary gets too complicated this gets very difficult to do.
If you are aggregating, you would want to say we have, for example, 10,000,000 to 12,000,000 specimens in Belgium. That is possible if you have a simple vocab, such as Precise count; Minimum; Maximum

**Comment by mswoodburn** [comment]
Deprecated in favour of MeasurementOrFact class
