### ISSUE TITLE
Class:TaxonQuantity

### ISSUE THREAD

**Issue by mtrekels** [tdwg/cd#86]
|  |  |
| ---- | ---- |
| **Parent** | ObjectGroup |
| **Definition** | Metric for recording counts or estimates of the number of taxa represented by the CollectionDescription. |
| **Repeatable** | Yes |
| **Relationships** |  |
| **Potential standards/vocabularies/ontologies to adopt** | |
| **Notes** |  |

**Comment by mswoodburn** [comment]
Changed the parent to ObjectGroup, due to removing the CollectionDescriptionMetric class

**Comment by mswoodburn** [comment]
Deprecated in favour of MeasurementOrFact class
