### ISSUE TITLE
Property:taxonRank

### ISSUE THREAD

**Issue by mtrekels** [tdwg/cd#87]
|  |  |
| ---- | ---- |
| **Definition** | As a metric, the taxonomic rank identified to. |
| **Existing property** |  |
| **Existing class** |  |
| **Existing property identifier** |  |
| **Format** | Text |
| **Required** | Yes |
| **Repeatable** | no |
| **Constraints** | Controlled vocabulary |
| **Examples** | Kingdom; Order; Genus; Species |
| **Notes** |  |

**Comment by falkogloeckler** [comment]
This would be like https://terms.tdwg.org/wiki/abcd2:TaxonIdentified-HigherTaxonRank

**Comment by mswoodburn** [comment]
Deprecated in favour of MeasurementOrFact class
