### ISSUE TITLE
Property:taxonQuantity

### ISSUE THREAD

**Issue by mtrekels** [tdwg/cd#88]
|  |  |
| ---- | ---- |
| **Definition** | The quantity of taxa that are represented by the objects represented by the CollectionDescription. |
| **Existing property** |  |
| **Existing class** |  |
| **Existing property identifier** |  |
| **Format** | Integer |
| **Required** | Yes |
| **Repeatable** | no |
| **Constraints** |  |
| **Examples** | 10000 |
| **Notes** |  |

**Comment by mswoodburn** [comment]
Deprecated in favour of MeasurementOrFact class
