### ISSUE TITLE
Property:taxonQuantityConfidence

### ISSUE THREAD

**Issue by mtrekels** [tdwg/cd#89]
|  |  |
| ---- | ---- |
| **Definition** | A measure (precise or approximate) of the percentage error on the estimated taxon count. |
| **Existing property** |  |
| **Existing class** |  |
| **Existing property identifier** |  |
| **Format** | percentage |
| **Required** | Yes |
| **Repeatable** | no |
| **Constraints** |  |
| **Examples** | 5% |
| **Notes** |  |

**Comment by mswoodburn** [comment]
Deprecated in favour of MeasurementOrFact class
