### ISSUE TITLE
Property:taxonQuantityMethod

### ISSUE THREAD

**Issue by mtrekels** [tdwg/cd#90]
|  |  |
| ---- | ---- |
| **Definition** | The method used to count the taxa represented by the CollectionDescription. |
| **Existing property** |  |
| **Existing class** |  |
| **Existing property identifier** |  |
| **Format** | Text |
| **Required** | Yes |
| **Repeatable** | no |
| **Constraints** | Controlled vocabulary |
| **Examples** | Estimate; Precise count; Minimum; Maximum |
| **Notes** |  |

**Comment by mswoodburn** [comment]
Deprecated in favour of MeasurementOrFact class
