### ISSUE TITLE
Class:ObjectDigitalRecordMetric

### ISSUE THREAD

**Issue by mtrekels** [tdwg/cd#91]
|  |  |
| ---- | ---- |
| **Parent** | ObjectGroup |
| **Definition** |  |
| **Repeatable** | Yes |
| **Relationships** |  |
| **Potential standards/vocabularies/ontologies to adopt** | |
| **Notes** |  |

**Comment by mswoodburn** [comment]
Changed the parent to ObjectGroup, due to removing the CollectionDescriptionMetric class

**Comment by mswoodburn** [comment]
Deprecated in favour of MeasurementOrFact class
