### ISSUE TITLE
Property:digitalRecordType

### ISSUE THREAD

**Issue by mtrekels** [tdwg/cd#92]
|  |  |
| ---- | ---- |
| **Definition** | Type or level of digital record with reference to the object(s) that it describes |
| **Existing property** |  |
| **Existing class** |  |
| **Existing property identifier** |  |
| **Format** | Text |
| **Required** | Yes |
| **Repeatable** | no |
| **Constraints** | Controlled vocabulary |
| **Examples** | Object; Lot; Sample |
| **Notes** |  |

**Comment by mswoodburn** [comment]
Deprecated in favour of MeasurementOrFact class
