### ISSUE TITLE
Property:digitalRecordQuantity

### ISSUE THREAD

**Issue by mtrekels** [tdwg/cd#93]
|  |  |
| ---- | ---- |
| **Definition** | The quantity of digital records of the defined digitalRecordType that represent the objects within the Collection Description |
| **Existing property** |  |
| **Existing class** |  |
| **Existing property identifier** |  |
| **Format** | Integer |
| **Required** |  |
| **Repeatable** | no |
| **Constraints** |  |
| **Examples** | 26; 264; 99,657 |
| **Notes** |  |

**Comment by mswoodburn** [comment]
Deprecated in favour of MeasurementOrFact class
