### ISSUE TITLE
Class:DigitizationLevelAssessment

### ISSUE THREAD

**Issue by mtrekels** [tdwg/cd#94]
|  |  |
| ---- | ---- |
| **Parent** | ObjectDigitalRecordMetric |
| **Definition** | An assessment of the quantity or proportion of digital records or associated digital media that meet a defined set of criteria for presence, quality or completeness |
| **Repeatable** | Yes |
| **Relationships** |  |
| **Potential standards/vocabularies/ontologies to adopt** | |
| **Notes** | The scope of this class can include digital specimen records, associated or linked metadata, and digital media such as 2D and 3D images, audio files and video. |

**Comment by qgroom** [comment]
It is not clear if "digitization" refered to here includes imaging.
We perhaps either need to be more specific or have a clear definition of what digitisation means.

**Comment by rondlg** [comment]
There should be separate metrics to indicate level of "transcription" and level of "imaging".

**Comment by mswoodburn** [comment]
I think this can include digital records and digital media - it's pretty flexible, with what the level refers to described in the digitizationLevelDefinition property. I've tried rewording the definition and added notes to be clearer about the scope. 

We could add a digitalAssetType (or similar) property to the class to distinguish between 'record', 'image', 'audio' etc if it would be better to be explicit?

Might also be worth adding an 'assessmentSpecification' property to group records in the same scheme. E.g. for a MIDS assessment, you might have 4 DigitizationLevelAssessment records with digitizationLevelDefinitions of MIDS-0, MIDS-1, MIDS-2 and MIDS-4, and assessmentSpecification would be 'Minimum Information for a Digital Specimen (MIDS)' (or a url where available).

**Comment by mswoodburn** [comment]
Deprecated in favour of MeasurementOrFact class
