### ISSUE TITLE
Property:digitizationLevel

### ISSUE THREAD

**Issue by mtrekels** [tdwg/cd#95]
|  |  |
| ---- | ---- |
| **Definition** | Code or name for the digitization completeness level |
| **Existing property** |  |
| **Existing class** |  |
| **Existing property identifier** |  |
| **Format** | Text |
| **Required** |  |
| **Repeatable** | no |
| **Constraints** |  |
| **Examples** | Level 1; A; Inventory; Catalogued; MIDS1 |
| **Notes** |  |

**Comment by mswoodburn** [comment]
Deprecated in favour of MeasurementOrFact class
