### ISSUE TITLE
Property:digitizationLevelDefinition

### ISSUE THREAD

**Issue by mtrekels** [tdwg/cd#96]
|  |  |
| ---- | ---- |
| **Definition** | Definition of the digitization level to which the digital records or media conform |
| **Existing property** |  |
| **Existing class** |  |
| **Existing property identifier** |  |
| **Format** | Text |
| **Required** | yes |
| **Repeatable** | no |
| **Constraints** |  |
| **Examples** | `MIDS-2`, `Inventory`, `High resolution 2D image`, `Georeferenced`, `Taxonomy verified` |
| **Notes** | The definition may represent one level from a specified scheme of digitization levels. |

**Comment by mswoodburn** [comment]
Deprecated in favour of MeasurementOrFact class
