### ISSUE TITLE
Property:digitizationLevelQuantity

### ISSUE THREAD

**Issue by mtrekels** [tdwg/cd#97]
|  |  |
| ---- | ---- |
| **Definition** | The quantity of object-level digital records that conform to the DigitizationLevel |
| **Existing property** |  |
| **Existing class** |  |
| **Existing property identifier** |  |
| **Format** | Numeric |
| **Required** |  |
| **Repeatable** | no |
| **Constraints** |  |
| **Examples** | 140; 99; 200,000 |
| **Notes** |  |

**Comment by szucsichnikolaus** [comment]
take care that under 
Property:digitizationLevelQuantityType you also allow for percentage
so the Format changes from numeric to percentage then (dependent on Chosen type)

**Comment by mswoodburn** [comment]
Deprecated in favour of MeasurementOrFact class
