### ISSUE TITLE
Property:digitizationLevelQuantityType

### ISSUE THREAD

**Issue by mtrekels** [tdwg/cd#98]
|  |  |
| ---- | ---- |
| **Definition** | The type of quantification system used for the quantity of digital records at the defined digitization completeness level |
| **Existing property** |  |
| **Existing class** |  |
| **Existing property identifier** |  |
| **Format** | Text |
| **Required** |  |
| **Repeatable** | no |
| **Constraints** | Controlled vocabulary |
| **Examples** | Units; Percentage |
| **Notes** |  |

**Comment by mswoodburn** [comment]
Deprecated in favour of MeasurementOrFact class
