### ISSUE TITLE
Property:digitizationLevelSource

### ISSUE THREAD

**Issue by mtrekels** [tdwg/cd#99]
|  |  |
| ---- | ---- |
| **Definition** | Indicator of whether the DigitizationLevel data are calculated from the digital records, or manually estimated |
| **Existing property** |  |
| **Existing class** |  |
| **Existing property identifier** |  |
| **Format** | Text |
| **Required** |  |
| **Repeatable** | no |
| **Constraints** | Controlled vocabulary |
| **Examples** | Calculated; Reported |
| **Notes** |  |

**Comment by mswoodburn** [comment]
Deprecated in favour of MeasurementOrFact class
